### ISSUE TITLE
Remove of CONF_MONITORED_CONDITIONS and other selectors in backend

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/architecture#100]
Follow of https://github.com/home-assistant/home-assistant/pull/17618 and other PRs.

## Summary

We should simplify configs and that makes it also simpler for the new config flows. First, the backend should grab all information they are around in a way that the device/API not affect badly. That happens with a data object or throttling.

A user should not decide on backend what kind of data he wants on UI. He should also not know what kind of data is available for this interface. All should be simple, the user adds an integration and the data are available.

The selector for data is the UI. The user should see in future all data and can easily group that into the UI. So he sees on UI what kind of data are in the backend and see also the meaning of this. It's also simple possible to see now what are around.

## Reason

We want to be more user-friendly and everything configurable is not really userfriendly and make it hard to build a UI around this. Also, the entry level is very hard and all integration handle that a bit in the other direction. We should simplify all this integration to be an interface to grab data from it.

**Comment by balloob** [comment]
I agree. We can start with this once Lovelace is the default and no template entities are listening to all state changes

**Comment by tjorim** [comment]
This is not perfect in all situations.

E.g., in case of the coinbase component I was planning on integrating a 'monitored conditions' option for account wallet balances. Currently, each time Coinbase introduces a new wallet currency, a new sensor entity gets added to the system. When the user is not using LoveLace yet it's shown as well. This is just one of the cases I prefer to be explicit.

Would we remove selectors from existing components as well?

Currently `coinbase` already has `exchange_rate_currencies`. At the moment the user can specify which exchange rate currencies they would like to create sensors for. If there is no option to filter thise, it would get messy as hell. That would be 175 extra sensor entities; and although it won't be shown unless added to the LoveLace UI, it still gets added to the system.

**Comment by amelchio** [comment]
There is also an issue that this could cause the recorder database to explode in size. I expect the recorder to keep its `exclude` option but that is more of the unfriendly UI that we want to avoid.

**Comment by tjorim** [comment]
@amelchio Correct, that's one of the reasons https://github.com/home-assistant/home-assistant/pull/15888 got implemented. By default all attributes got logged, resulting in an immense database.
If the user needs to use the `exclude` of `recorder` we're just shifting the problem from one 'user-unfriendly' (it's not in my opinion) configuration to another.

**Comment by cgarwood** [comment]
If we get rid of monitored conditions and just pull all data in for all components we desperately need a way to exclude entities from being created. There’s some support in the entity registry for that but it has never been fully implemented. Some integrations have information that I don’t care about and I would prefer keeping it out of the database, state machine, and UI all together.

**Comment by tsvi** [comment]
@tjorim "Not added to Lovelace" doesn't cut it. Some sensors I really don't care for in my UI, but I'd like to keep a record for them.

**Comment by bachya** [comment]
I discussed this with @balloob last night because I arrived at a quandary with the `ambient_station` component:

1. `monitored_conditions` can be configured in `configuration.yaml`.
2. Because `ambient_station` can also be configured via config entry, on first "load", a config entry is created and the `monitored_conditions` value is added to it.
3. On each HASS restart, regardless of the `monitored_conditions` in `configuration.yaml`, the `monitored_conditions` stored in the config entry are used.
4. Once the config entry exists, HASS startup for that component begins there; `configuration.yaml` values are ignored forevermore.

So, this means that if a user implements `ambient_station` in `configuration.yaml`, they get one chance to define the `monitored_conditions` they want; after that, the only ways to alter them are to (a) delete the config entry and restart HASS or (b) alter the config entry registry directly.

I'm new to the discussion and don't understand all of the implications, I'm sure, but at first glance, I'm a fan of integrations adding _all_ of their entities and Lovelace being responsible for what's shown or not.

**Comment by Kane610** [comment]
When options for config entries are done you will be able to configure stuff like this in the frontend and also possibly allow to act without restart. 

For certain components there will be differences between what users want out of the component and possibly performance issues if there is not a way to limit what should be exposed. It needs to be user friendly and simplistic. But powerful enough to scale well.

**Comment by bachya** [comment]
@Kane610 Got it; thanks for that info. Considering this (and reading the comments on Reddit this morning), I think it's worth having a larger discussion (if it hasn't happened already) on what our stance on "suggested/desired" configuration methods are going forward. Discussion here: https://github.com/home-assistant/architecture/issues/143

**Comment by pvizeli** [comment]
ADR003
