### ISSUE TITLE
Standardize meaning of 0% brightness for light component

### ISSUE THREAD

**Issue by emontnemery** [home-assistant/architecture#119]
**Background:**
Setting a light to 0 brightness behaves differently for different platforms.
For some platforms, 0 means minimum brightness and for some platforms it means the light is off.
This gives a very inconsistent user experience.

**Proposal:**
Update light component to document the expected behavior when brightness is set to 0.

Either:
1. Setting the brightness to 0 turns off the light (I personally think this is the better option).
2. Setting the brightness to 0 sets the minimum brightness supported by the hardware.

**Comment by OttoWinter** [comment]
Anotzer inconsistency: Should the white value scale with brightness? For some platforms 50% brightness and 100% white value is white led 100% on, others 50% on.

**Comment by Kane610** [comment]
This might differ between hubs and also between fw of devices on same host. This will be hard to standardise

**Comment by emontnemery** [comment]
@OttoWinter Good point, maybe extend this issue to cover some more inconsistencies with lights then? Another inconsitency is the expected behavior if a white or color temperature is set, depending on the hub it will:
- Turn off RGB LED and set the white LED(s) brighness
- Keep RGB LED unchanged, and set the white LED(s) brightness

**Comment by emontnemery** [comment]
@Kane610 Sure, it might not be hard to standardize, but it will be easier if there is at least documented expectations of how a light should behave.

**Comment by balloob** [comment]
I think that we should remove the option to set 0 brightness.

**Comment by emontnemery** [comment]
> remove the option to set 0 brightness.

Interesting. This is how the Philips Hue API is designed.
It would make templating a bit annoying because it's not enough with an action `light.brightness` and just template the brightness but maybe that's OK.

How should this be enforced, apart from updating the documentation to something like:
`Brightness: Integer between 1 and 255 for how bright the light should be. Brightness 1 is the minimum brightness supported by the light.`

**Comment by balloob** [comment]
Update the voluptuous schema to make it an invalid option.

**Comment by armills** [comment]
If we get rid of the option to set brightness to zero, would we have a good option for users who are using template values or scripts, to dynamically either set the brightness level or turn the light off?

What if calling the service with brightness zero was translated by the service to explicitly call `turn_off` on the entity?

**Comment by emontnemery** [comment]
> What if calling the service with brightness zero was translated by the service to explicitly call turn_off on the entity

I think this sounds very good!

**Comment by balloob** [comment]
I don't think that we should have architectural decisions for brightness support in the light entity be influenced by templated service calls in the script syntax. That should be fixed in the script syntax?

**Comment by balloob** [comment]
Adam is right. We are the consistent API. Otherwise we can't have other integrations rely on our data model, like Google Assistant, Alexa or whatever comes next.

I agree that we should have a solution before we strip the possibility, especially now that we cancel scripts/automations on invalid service data. I'll open a new architecture issue.

**Comment by balloob** [comment]
Created a new issue to discuss the invalid service data issue.

**Comment by OttoWinter** [comment]
@armills Yes you're right there. The thing I was after (and failed to formulate clearly) was that if we choose to standardize this to "0 means off" we're _removing_ an important ability which I personally value: having the option to set the loerst possible brightness. With the new system the lowest you could go would be 1/255 brightness which is quite dim, but many controllers support far less than that.

Thinking about this again, I am definitely in favor of consistency, but I don't want it to take away an important feature.

So... another issue with the loght platform (which could be an entirely new architecture issue) is: having brightness (and rgb etc) be floats. I mean there's not really a reason I can think of why the service call (+ attributes) should be limited to bytes from 0 to 255.

**Comment by emontnemery** [comment]
@OttoWinter:
> A reason for not making it call OFF on 0%: With RGBW[W] lights you sometimes only want the white lights to be on, for example for DIY light strips. Most of the time you want to use the white channel because its color is way more accurate than the other channels (especially for cheap LED strips). So set brightness to 0% and white value to 100%

Are you saying `brightness` of an RGBW[W] light should only control the red, green and blue channels?
That doesn't sound very intuitive..

Have a look at #123, it's for the RGBW case, RGBWW is basically the same issue though.

**Comment by emontnemery** [comment]
@balloob, @armills, @OttoWinter So, which option can we decide on:
 1. Setting the brightness to 0 turns off the light.
 2. Setting the brightness to 0 is not allowed.

(My vote is on option 1)

**Comment by OttoWinter** [comment]
Of the two, my vote would also be 1 - since it makes writing templates much easier.
But I can live with both too.

**Comment by dgomes** [comment]
[DALI](https://en.wikipedia.org/wiki/Digital_Addressable_Lighting_Interface) which is an international standard for light control in buildings uses 0 as OFF.

My vote goes for option 1.

**Comment by armills** [comment]
I prefer option 1 as well, although I'd be OK with either.

**Comment by balloob** [comment]
Let's do option 1

**Comment by amelchio** [comment]
I recently made home-assistant/home-assistant-polymer#1715 which _removed_ the turn_off functionality when setting the UI slider to the minimum position.

Nevertheless, I am fine with option 1 in the current case. There is a difference between a UI that is easy to trigger by accident and a handy shortcut in an API.

I would probably prefer to retire `brightness` and only have `brightness_pct` with 0 meaning off, 1 meaning as dim as possible and 2-100 being an increasing amount of brightness that the platform can scale as appropriate.

**Comment by mvdwetering** [comment]
It seems I just found this topic a couple of hours too late but I would go for option 2.

1) In general it is bad to combine/couple different responsibilities. 
Turning a light on/off is different from changing the brightness. 
I can turn a light off at any brightness, why should brightness 0 be special?
Also if 0 brightness would turn the light off would that also mean that turning a light off sets the brightness to 0?
Does this also mean that setting a brightness when a light is off will turn it on? Will a light also turn on when I set a color(temperature)?

2) Depending on the lights you have there may be a big difference in light output between lowest brightness (but still on) and no light (off). So it is desirable to have the distinction between turning the light off or setting lowest brightness.

Having 0 turning off the lights will make it hard to set the lights to the lowest brightness where they still emit light.

If you build the typical slider UI to control brightness it will be really hard to set the lights to a low brightness since you will be turning the lights off instead when just dragging the slider to the left (when just using the full brightness range). Or you have to exclude the 0 from the slider range, but that just shows that this is a special case.
If you would build an automation that dims light up and down with buttons you have to think about including the 0 in the range or not to avoid the lights turning off when you just wanted to dim down the lights (e.g. to make the room more cozy, not fully dark).

**Comment by michaelarnauts** [comment]
Setting a bulb to 0 percent brightness might still be something else then turning the light off. In case of a smart bulb, it could be that the bulb is still receiving power and connected trough some wireless protocol when the brightness is at 0, while it can be that the bulb is disconnected from the net when it's turned off.

Like a AVR that's at 0% volume, but still turned on.

**Comment by amelchio** [comment]
@michaelarnauts Maybe those platforms should set the brightness to 0 when turned off in HA? It seems rather useless to have it disconnect from the net but such functionality could be provided in a platform specific service call.

**Comment by emontnemery** [comment]
How do we enforce that settting brightness to 0 turns the light off? Does this need to be taken care of in each platform, or can it somehow be handled in the base component?

**Comment by balloob** [comment]
It should be taken care of by the `light.turn_on` service handler in the light component. That way it's not up to integrations to do something.

**Comment by emontnemery** [comment]
I think this is all done, closing
