### ISSUE TITLE
Standardize behavior of light `white_value`

### ISSUE THREAD

**Issue by emontnemery** [home-assistant/architecture#123]
**Background:**
Behavior when setting a an RGBW light's `white_value` differs between platforms due to the fact that some HW supports a color and white simultaneously, this is for example the case for ZWave lights, whereas some HW does not support it, this is for example the case for Philips Hue.

To make things worse, the frontend component is ambigous not really suitable for either of the two options:
![image](https://user-images.githubusercontent.com/14281572/50242749-8cfac580-03cb-11e9-8ec7-c4456d97dc6f.png)

**Proposal:**
Add a new property to the light component which defines if the light supports setting a color and a white level simultanesously.

If it does, frontend should show something like this:
![image](https://user-images.githubusercontent.com/14281572/50243073-6be6a480-03cc-11e9-8b48-c382e3e2abf8.png)

If it does not, frontend should show something like this:
![image](https://user-images.githubusercontent.com/14281572/50243270-0fd05000-03cd-11e9-9eb4-b96fb7b52e08.png)

**Comment by amelchio** [comment]
This seems complicated. Maybe we should start by describing why we even need a separate control for the white level ... how is this not covered by a combination of the master brightness and the saturation (i.e. white level) in the color wheel?

**Comment by emontnemery** [comment]
A separate control is needed because the white channel can be expected to be much brighter than the red, green and blue channels in many cases.
If you do it just with the colour wheel, you either need to calibrate and you don't use the full brightness of white channel, or the light gets much brighter at low saturation.

**Comment by amelchio** [comment]
> or the light gets much brighter at low saturation

So turn it down. Why does that need a separate slider named "white"?

**Comment by emontnemery** [comment]
> Why does that need a separate slider named "white"?

It doesn't really, as you correctly point out. It's however not an easy problem to decide when to start turning on the white channel, and by how much, as saturation decreases. Maybe especially so for generic multi-channel dimmers where the characteristics of the light sources can not be known.

By the way, this is only an issue for HW where the API supports individual control of 4 channels.
In the cases where they don't and the HW decides, do you agree this kind of UI makes more sense:

![image](https://user-images.githubusercontent.com/14281572/50290450-fdf1ba00-046b-11e9-925b-fb5b940b6081.png)

**Comment by emontnemery** [comment]
How about exposing the capability of the W channel through `supported_features`, attributes, perhaps:
`SUPPORT_INDEPENDENT_WHITE_CHANNEL = 256`

**Comment by amelchio** [comment]
What you are proposing is, I think, the existing [`SUPPORT_WHITE_VALUE`](https://github.com/home-assistant/home-assistant/blob/2c07bfb9e0ac03fdf74b83152f4511ed7f7104b0/homeassistant/components/light/__init__.py#L41).

The problem (as your issue title also states) is that we do not have rules about how lights should handle this value and I think it really comes down to this:

* When setting `white_value`, is `brightness` (i.e. RGB) automatically set to zero?
* When setting `hs_color`/`brightness`, is `white_value` automatically set to zero?

We should decide this at the `light.turn_on` service level and adjust the UI from that decision.

**Comment by emontnemery** [comment]
@amelchio I'm proposing to support two different behaviors depending on the light's capabilities:
- `SUPPORT_WHITE_VALUE = True and SUPPORT_INDEPENDENT_WHITE_CHANNEL = False`
  When setting `white_value`, color channels (i.e. RGB) are set to zero.
  When setting `hs_color`, white channel is set to zero.
- `SUPPORT_WHITE_VALUE = True and SUPPORT_INDEPENDENT_WHITE_CHANNEL = True`
  When setting `white_value`, color channels (i.e. RGB) are NOT set to zero.
  When setting `hs_color`, white channel is NOT set to zero.

By the way, why is `brightness` only for RGB?
That's not the case for simple dimmable lighs, lights with adjustable color temperature and also not for RGBWW lights, i.e. lights with RGB and adjustable color temperature, so why would it be the case for RGBW lights?

Proposed frontend for `SUPPORT_WHITE_VALUE = True and SUPPORT_INDEPENDENT_WHITE_CHANNEL = False`:
![image](https://user-images.githubusercontent.com/14281572/57190373-a97e4100-6f19-11e9-8247-41edd20ef539.png)

Proposed frontend for `SUPPORT_WHITE_VALUE = True and SUPPORT_INDEPENDENT_WHITE_CHANNEL = False`:
![image](https://user-images.githubusercontent.com/14281572/57190382-d0d50e00-6f19-11e9-9197-0e2b311a5d11.png)

**Comment by OttoWinter** [comment]
@amelchio 
> When setting white_value, is brightness (i.e. RGB) automatically set to zero?

Well that's not really possible because #119 turns a light off when brightness is set to zero.

I agree that we should first focus on what `white_value` really means for a light - and only then talk about UI. Let's think about this using an RGBW light as an example.

Currently, I think the value given to an W channel of a light are loosely defined as being `w_channel = state * (brightness/255) * (white_value/255)`. When the light is off the w channel is also off and the w value scales with both `brightness` and `white_value`.

The problem with that is that (as @emontnemery said) - it's impossible to control only the white value of the light (and disable the RGB channels). Why? Well if I want to disable the RGB channels I need to set `brightness = 0`. But... that also turns off the light (#119) and thus the white channel.

IMO, ideally lights should be able to tell the core that they support "independent" operation of the white value. That means the user can switch between (1) RGB color mode and (2) white_value mode.

1. `(r_channel,g_channel,b_channel) = state * (brightness/255) * ((r,g,b)/255)` - `w_channel = 0`
2. `(r_channel,g_channel,b_channel) = 0` - `w_channel = state * (brightness/255) * (white_value/255)`

Next question is how this should be represented in the service call attrs and state attrs. One option might be magic value for `hs_color` like `None` though that could prove to have some difficulties. Another option might be to have it coupled to `white_value` - so if `white_value > 0` then color is assumed to be disabled and only the white channel is on.

**Comment by amelchio** [comment]
I don't think there is any current definition, it's just a mess. I guess we each see this differently, based on the lights that we have experience with.

My bulbs (LIFX and MiLight) do have color and white modes. I select between the modes with `hs_color` and `color_temp`. The `brightness` works for both modes. This supports any setting that my lights can do and I think it matches the capabilities of many bulbs (but I could be wrong).

I see `white_value` as a corner case for when RGB __and__ W should both be on at the same time. As I understand it, this is mostly with dimmers where the characteristics of the light sources can not be known, as was mentioned above.

I will not type more before I understand whether we agree this far :)

**Comment by OttoWinter** [comment]
> I don't think there is any current definition, it's just a mess.

True :) I hope with this architecture issue we can come up with a definition what each value means exactly (as a mathematical formula).

> My bulbs (LIFX and MiLight) do have color and white modes.

Does that mean they only support RGB mode OR W mode at a time, or can W be controlled independently (via API I mean)? In my previous post, I mostly talked about the "either RGB or W" case, but if most lights support independent W channel control, then we might also consider the "RGB and W control" case.

> I see white_value as a corner case for when RGB and W should both be on at the same time.

Ok. What would R,G,B,W = 0,0,0,255 (only white channel on) be represented as?

Anyway, I think any approach would need to follow these rules:

- If the light is OFF, all channels are 0.
- Brightness scales *all* channels - so 50% brightness means R, G, B and W are at most 50% on.
- (As a result: Brightness 0 means the light is OFF.)

**Comment by amelchio** [comment]
I don't think we can do a mathematical formula. For example, we have a saturated color when one or two RGB LEDs are on. To desaturate that color, we could power on the remaining RGB or we could power on the white LED. My bulbs do not have an API to pick between those two ways so it would not be possible to adhere to a particular formula.

> Does that mean they only support RGB mode OR W mode at a time, or can W be controlled independently

It is OR. But these are just modes; how the LEDs actually operate is not defined. Color can be washed out by white and any white temperature can be constructed from RGB.

For example, see https://developers.meethue.com/wp-content/uploads/2018/02/color.png – white is a mix of RGB.

>  What would R,G,B,W = 0,0,0,255 (only white channel on) be represented as?

I am not sure what you are asking. If I want white light, I set e.g. `kelvin: 2900`. I don't know which LEDs are used to emit that ... and I don't much care, as long as it mixes to warm white.

**Comment by OttoWinter** [comment]
> My bulbs do not have an API to pick between those two ways so it would not be possible to adhere to a particular formula.

Good to know - I didn't know how granular the API access on other platform is.

> It is OR. But these are just modes; how the LEDs actually operate is not defined. Color can be washed out by white and any white temperature can be constructed from RGB.

So you're talking about bulbs that internally really are "just" RGB lights? I've been talking about lights that have a dedicated secondary white channel. 

Please forgive me asking, but if the lights you're talking about in the end are just RGB lights, why then have white value in the first place? Doesn't the hs_color property fully define what the light should be emitted?

To clarify, the way *I* think of white value is for separately controlling the white channel on an RGBW light (where the color channels can be used for fancy colors - and the white channel for accurate white light).

**Comment by amelchio** [comment]
> So you're talking about bulbs that internally really are "just" RGB lights?

No, they are RGBW/RGBWW. That does not matter though. I just care which colors/whites they can make, not how they do it.

> Please forgive me asking, but if the lights you're talking about in the end are just RGB lights, why then have white value in the first place?

I do not use `white_value`. That is why I call it a corner case.

> To clarify, the way _I_ think of white value is for separately controlling the white channel on an RGBW light (where the color channels can be used for fancy colors - and the white channel for accurate white light).

This is covered by `hs_color` and `color_temp` (`kelvin`).

I only see a need for `white_value` when we want `hs_color` and `color_temp` active at the same time.

**Comment by OttoWinter** [comment]
> No, they are RGBW/RGBWW. That does not matter though. I just care which colors/whites they can make, not how they do it.

Yes, that makes sense for those bulbs.

However I still think by that rationale, why have white value and color temperature at all? If you know the exact light emission behavior of a light, you can perfectly model the output with just `brightness` and `hs_color`. Then the color wheel together with brightness will already give you all possible light colors. So no need to have `color_temp` (and therefore neither `white_value`).

The side which I'm coming from to this architecture issue (and from what I understand why @emontnemery suggested this too), is that when you *do not* know these emission factors (i.e. the light is not calibrated as is the case with *all* RGBW strips you buy online). And these are not niche products either - commercial LED strip dimmers like the H801 are quite common due to their unbeatable price.

As @emontnemery said,

> It doesn't really, as you correctly point out. It's however not an easy problem to decide when to start turning on the white channel, and by how much, as saturation decreases. Maybe especially so for generic multi-channel dimmers where the characteristics of the light sources can not be known.

For these generic dimmers, you either:

1. Calibrate the characteristics through a complicated process
2. Use an extra attribute/slider to control the white (+ warm white) channel of the light, as has been done for many lights in the past with the `white_value` attribute.

As I said before, for the lights where the characteristics are known, I do not see a reason for color_temp/white_value - why not leave this attribute for (2) of this list?

To clarify, I can live with many solutions to this problem - Myself I would just appreciate a common definition of white_value.

**Comment by amelchio** [comment]
Okay, I think that I understand your viewpoint now. Thanks for bearing with me.

So in this situation it seems that to get full control you actually need `color_value`, `warm_white_value`, `cold_white_value` and finally a master `brightness`?

**Comment by OttoWinter** [comment]
> So in this situation it seems that to get full control you actually need color_value, warm_white_value, cold_white_value and finally a master brightness?

It could be done like that, but I don't think it will be easy to get that many attributes added. Plus the mixing between cold and warm white can actually be estimated quite well, only the differentiation between RGB and W[W] cannot.

The way I propose this should work for the kinds of lights I talked about, is:

1. Facts that should always hold

  - `state` controls entire light - OFF means R,G,B,W[,W] are all off.
  - `brightness` controls brightness of all channels: 0 brightness means light is OFF - 50% brightness means all channels are at most 50% on.

2. `white_value` extensions - this represents the sub-brightness of the white channels (cold white and warm white).

  - `white_value` is an additional property that controls the white channel - the `hs_color` setting does not impact white channel value.
  - `white_value` at 50% means the W (and warm white) channel are on at 50% of the master brightness. So W channels are `(brightness/255) * (white_value/255)`

3. `color_temp` - Color temperature controls how much of cold white and how much of warm white channel is on.

  - at the coldest possible `color_temp`, only the cold white channel is on. warm white is off. 
  - at the warmest possible `color_temp`, only the warm white channel is on. cold white is off.
  - in between, both are on - integrations can choose their own way to mix how much each cw and ww is on.

So for an RGBW light the channels would be defined like this:

- `R = int(state == 'ON') * (state.brightness/255) * (state.color_as_rgb[0]/255)`
- `G = int(state == 'ON') * (state.brightness/255) * (state.color_as_rgb[1]/255)`
- `B = int(state == 'ON') * (state.brightness/255) * (state.color_as_rgb[2]/255)`
- `W = int(state == 'ON') * (state.brightness/255) * (state.white_value/255)`

For an RGBWW it would be like this:

- R, G, B as before
- `CW = int(state == 'ON') * (state.brightness/255) * (state.white_value/255) * (state.color_temp-state.min_color_temp)/(state.max_color_temp-state.min_color_temp)`
- `WW = int(state == 'ON') * (state.brightness/255) * (state.white_value/255) * (state.max_color_temp-state.color_temp)/(state.max_color_temp-state.min_color_temp)`

(naive formula - actual mixing between cw/ww channels is not usually linear)

Disclaimer: The above is from ESPHome - this light representation has worked quite well with actual hardware and has gone through a lot of improvements to end up there.

---------

The above gives control of the white channels of the light. There's one problem though: it's not possible to *only* activate the W[W] channel and turn RGB off.

The problem is that `hs_color` can currently not be "switched off". hs_color will always point to *some* hue/saturation - so as long as `brightness > 0`, at least one of the *color* channels will be on.

Suggested solution: There are plenty, @emontnemery 's solution of switchting between color and white mode sounds good. Another option would be to define `white_value = 0` to mean "color-only mode - disable all white channels ", and define `white_value > 0` as "only white is on, with adjustable color temp".

**Comment by emontnemery** [comment]
> Another option would be to define `white_value = 0` to mean "color-only mode - disable all white channels ", and define `white_value > 0` as "only white is on, with adjustable color temp".

That's possible, but i think it's maybe a bit hackish? Anyhow, either your suggestion or mine will both work just fine for lights that don't support turning on white channel(s) and color channels at the same time. 

This seems to be the case for most consumer oriented lights, for example Philips Hue just to name one.

ZWave seems to be an exception though, as the protocol _explicitly_ states all channels must be possible to control independently. To be more specific, ZWave specifies:
- One master brightness which controls all channels
- One brightness value for each channel (R, G, B, WW, CW)

(Cheap Chinese LED dimmers also all support independent channels.)

If we want to support this kind of control in HA, there is no choice but to either add a `color_brightness` property, or to add a `master_brightness` property.

**Comment by OttoWinter** [comment]
> That's possible, but i think it's maybe a bit hackish? Anyhow, either your suggestion or mine will both work just fine for lights that don't support turning on white channel(s) and color channels at the same time.

It is - the reason I suggested that was I find it is a compromise between keeping the existing light model (no major breaking change) and fixing the functionality. The hardware I'm talking about can control each channel individually as you said too.

At least for me, a `color_brightness` or even `master_brightness` sounds like quite a hack too. Especially since `brightness` already exists. Plus I don't know of a good way to expose that via any frontend - Adding yet another slider for color brightness would just be too confusing.

I find re-defining what `white_value` means the least intrusive option while still allowing for the functionality: white channel control. (Technically not even re-defining as it doesn't appear to ever have been formally defined anyway).

**Comment by ivmi** [comment]
I'd like to propose a different approach. Since we would like to give as much control as possible to the user, and keep the behavior of lights consistent, how about splitting the rgbw light to separate entities:
- one for rgb lights with brightness, color wheel and on/off
- one for each white light (warm, cool, ...) with brightness and on/off

It would address the common usage scenario (to use the wight light most of the time, rgb as needed). 

Would it be feasible to do with the framework?

**Comment by amelchio** [comment]
That's an interesting approach. Could `light.group` work as a master brightness in such a setup?

**Comment by dolenec** [comment]
My question:
https://community.home-assistant.io/t/shellyforhass-custom-component/120801/36

**Comment by emontnemery** [comment]
I think the proposal from Otto https://github.com/home-assistant/architecture/issues/123#issuecomment-490929787 is really good, it would achieve the goal of representing the states of all RGB+W and RGB+WW lights unambiguously without adding any new states.

**Comment by emontnemery** [comment]
https://github.com/home-assistant/architecture/discussions/519
