### ISSUE TITLE
Calibration_factor attribute for sensors?

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/architecture#135]
Many sensors are reporting measurements of physical factors, e.g. temperature. As noted in the forums, some sensors (e.g. [Hue](https://community.home-assistant.io/t/hue-motion-sensors-remotes-custom-component/27176/677)) have a known issue where the sensor values are systematically incorrect. This can be resolved by applying a factor to the sensor value. As this is potentially a common issue, perhaps we should have a `calibration_factor` attribute for sensors, such that `sensor_value = sensor_reading * calibration_factor`?

Ref https://github.com/robmarkcole/Hue-sensors-HASS/issues/106

**Comment by OttoWinter** [comment]
Well the thing with that is that it can get arbitrarily complex. In my experience, most sensors have a constant **offset** to the real value - especially for temperature and humidity sensors.

Also, I don't think it's really possible with the current architecture to achieve an option for all sensor platforms. I would recommend using the `sensor.filter` platform (and adding filters there if necessary).

**Comment by robmarkcole** [comment]
Yes I agree it can get complex. My training is as a physicist, and if we wanted to be really precise you would characterise the `calibration_factor` as a function of e.g temperature & humidity etc. As you say we have other methods in HA to post process readings

**Comment by yottatsa** [comment]
From what I know from civil engineering, the temperature in a room depends on height non-linearly, and usually differs for about a 1.5*C / 1m. Moreover, our perception of room temperature is also depends on temperature on different heights, like the temperatures around legs and head.

So instead of calibrating each sensor to be precise I’m placing them on different heights and averaging to the abstract room temperature. This adds both precision and redundancy to the setup. I’m planning to release this `sensor.room` CC when I’ve got more time.
