### ISSUE TITLE
Add Appliance Entity Component

### ISSUE THREAD

**Issue by andrewsayre** [home-assistant/architecture#159]
This is a proposal to create a new component (`EntityComponent`) for household appliances (shortened to `appliance`), such as smart washers, dryers, and dishwashers.  Some of the more commonly available devices are made by Samsung and are integrated into SmartThings.  Without a concrete entity type, these end up getting represented as 4-6 sensors with no way to control without custom services on the SmartThings platform.  Given the availability of smart appliances (even outside of SmartThings), there is value in creating a formal entity to represent them.

#### Properties:
- `machine_mode`: (_required_) describes the current mode set by the user (i.e. `running`, `stopped` or `paused`) and is of one of the supported states.  All platforms would need to map to a fixed set of constants.  This would drive the entity `state` property.
- `supported_machine_modes`: (_required_) A list of states that are supported by the appliance (mapped to the component constants).
- `operating_state`: (_optional_) describes the actual activity occurring on the appliance (within the given mode).  For example, `rinsing`, `cleaning`, etc...  The possible values would be defined by the platforms.
- `completion_time`: (_optional_) Identifies the `datetime` of when the current mode will complete, or `None` if not supported or not applicable.

#### Services/commands:
- `set_machine_state(machine_state)`: (_required_) sets the `machine_state` to one of `supported_machine_states`.

### `SUPPORT_JOB_MODE` feature:
This feature allows setting the program mode to the running state of the appliance, if supported.

#### Properties:
- `job_mode`: (_required_) describes the job configuration of the current `machine_mode`.  This always returns the programmed mode, regardless of `machine_mode`.  This would be a variable string defined by the platform but one of supported job modes.
- `supported_job_modes`: (_required_) A list of modes supported by the appliance.  Defined by the platforms.  Same list of options regardless of `machine_mode`.

#### Services/commands:
- `set_job_mode(job_mode)`: (_required_) sets the `job_mode` to one of `supported_job_modes`.

### UI Presentation
I'm imaging the card would look and work similar to the climate entity.  Instead of showing a temperature dial,, it would have a device-class specific graphic resembling the type of device and in the middle it would show `operating_state`, `job_mode`, and `operating_time`.  Below the graphic would be the `supported_machine_modes` with the ability to click to activate.  We could mimic the real device and put the mode buttons at the top -- all depends on what graphics we come up with.

**Comment by balloob** [comment]
I don't think that we should group all appliances in one. This touches a design decision that Home Assistant has made early on. Contrary to other platforms, we create entities based on device type, not capability. This has made it a lot easier for our users to create a UI or do automations, makes it slightly more difficult to integrate with capability based systems and can end up tricky if a device doesn't fit in our abstraction. 

A light and a switch are very similar, both are on/off, yet we have different entity components for them. However, as both abstractions have grown, switches ended up adding features for current power user and lights added brightness, colors etc. If we would have put it all under 1 nomer "switch" early on, we would have ended up with a big mess, or with a breaking change because we had to split it up. Splitting up ended up happening when we split water heaters out of the climate component.

So I think that a generic "appliance" is not a good idea. We should have separate `laundry_machine`, etc.

**Comment by andrewsayre** [comment]
Makes sense.  I'd propose we go with `laundy_machine`, `washing_machine`, and `dishwasher` with similar attributes/commands -- instead of generalized would be specific, like `laundry_mode` instead of `machine_mode`.  

Let me see which is the highest priority to start and I'll open a new issue to describe.
