### ISSUE TITLE
Users & Authentication

### ISSUE THREAD

**Issue by fanthos** [home-assistant/architecture#17]
We have HTTP api support in HA, but currently only has password auth supported.

If password leaked accidently, we have to change the API password on HA and every device that using the API with password.

I think we should have more authentication method,  like public key and HMAC, to prevent use same password everywhere. Also, we can also support multiple user pass pair.

**Comment by balloob** [comment]
So I think that this is indeed part of a bigger story: users, authentication and authorization (permissions). We should think of solutions that are capable of all yet can be implemented 1 piece at a time.

- I think that for design I would want to take inspiration of some mature systems, like [Django](https://docs.djangoproject.com/en/2.0/topics/auth/). It would even be nicer if we could be API compatible and just support their auth providers 😉 
- At what level should we do authorization? I would expect API level (HTTP, WebSocket). All HTTP views already have names and thus are easy to do auth for, like `api:states`

**Comment by fanthos** [comment]
According to [`django.contrib.auth.backends`](https://github.com/django/django/blob/master/django/contrib/auth/backends.py), I think its not hard to make them compatible mostly, but hard to use their auth providers.

AWS4 looks a good reference for HMAC implement. ref https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

**Comment by fanthos** [comment]
Entity id residents in json data, so I think per-entity permission should be the hard part of the issue.
Currently user auth status accessible in `View` by `request[KEY_AUTHENTICATED]`, and it cannot be accessed elsewhere, so if we want to add multi-user support, the `username` should be somewhere better than the `request` object..
The pluggable authentication should not that hard to implement.

**Comment by balloob** [comment]
For MVP, let's limit to HTTP Views. Going down the rabbit hole of per entity permissions and many things will require a major refactor. It requires passing auth along with service calls (as we don't know which entity it will impact until it is processed). And yes, that does mean that allowing access to the call service permission is way too broad, but that should be solved later.

**Comment by pvizeli** [comment]
We need also support the old token system because there are a lot scripts/3-party application they work with this, maybe only for the API.

**Comment by fanthos** [comment]
Permission per view sounds good. We can add special code on service call to make it works with permission.
The token system could also "pluggable" by using something like `username:token`.

I think the `auth` could become a `platform`.

**Comment by balloob** [comment]
I think that you're confusing what is a component and a platform: https://home-assistant.io/developers/architecture_components/

Also, I don't think that we have too many components. Components organize things, platforms implement things. Components will take care of auth, maybe some extra services. Seems just fine.

The existing authentication via a token can be provided as one of the pluggable backends. Auth should not be a component or a platform. Authentication and authorisation is a core part of Home Assistant. It's a foundational functionality. I would expect them to live in `homeassistant/auth/` folder.

**Comment by fanthos** [comment]
I agree that `auth` should in core part of Home Assistant, but some other core feature like `http` `system_log` already  in `homeassistant/components`.

Currently we have 150+ `*.py` in `homeassistant/components/`.

**Comment by akatrevorjay** [comment]
It would be awfully nice to have nice syntactic sugar for HTTP views ala simple RBAC that is *handed* an actual authenticator that provides a raw interface. We'd need to expose required inputs since it varies per ofc, such as otp needing a token, but thinking ahead, this will vary quite a bit, ie oauth2, krb, u2f, etc.

@fanthos I totally agree if we can just *reuse* an existing framework's API and get what it comes with for free, that sounds amazing.

> Thinking way far ahead: Having an optional namespace would allow dynamic registrations inside of a component. 
This could provide a safer haven for things like the credentials that huemulation generates, which I quite like the thought of as currently it's kind of interspersed with variable data iirc.
(I think this may matter more so in my toy branch; I started adding in v2 huemulation, but it's not complete yet.)

**Comment by akatrevorjay** [comment]
Yeah, since since this will, at least eventually, become part of the API that is provided to the individual device/platform modules, I don't know where else it could even go.

IMO, preferably the pluggable parts (ie auth backends) wouldn't rely on being part of the homeassistant namespace at all, but maybe you have different thoughts on that. Personally, I find namespaced modules in Python to be cludgy at best. 

Just thinking aloud here,how everyone else handles middlewares is really simple and works quite well; that is at least being *able* to use a full import path of a class if you want to. Of course, simple aliases could be exposed to avoid having to type the full dotted quad like we're used to for the rest of the configuration. Thoughts?

**Comment by fanthos** [comment]
Basic features should in `core`, like password authentication, permission, built-in group(role), built-in user.

I think using `auth` component could make the backend pluggable easier. We can add new auth backend by simply put a file to config dir.

**Comment by akatrevorjay** [comment]
Being able to pip install it seems like it may be a win to me at least since you can keep it up to date just alike any other package, dependencies on X version of hass is then handled too. I could be missing something however!

**Comment by JensTimmerman** [comment]
My wishlist:
 - encourage users not to use a blank or default password 
 - save passwords hashed with a salt and strong hashing function
 - don't save passwords in cleartext in localstorage in the browser 
   - save session keys (encrypted cookies marked httponly vs localstorage? *
 - support for multiple users with different permissions (e.g. read only / restarting server/ reloading or changing config)
 - support for device/component specific passwords (tokens?)
 - allow users to easily remove certain devices/components and invalidate (all) open sessions 
 - audit log of when passwords are added, when and where logged in from (log ip)
  - notifications when logging in from new geolocations (email?)
  - notifications on brute forcing (email?)
 - 2nd factor authentication (TOTP ?)
 - warnings when doing all of this on encrypted connections 
  - support to auto redirect from http to https
  - support for optionally setting HTTP Strict Transport Security (HSTS) headers


I am willing to do some coding work on this if an architectural change is approved.

**Comment by OttoWinter** [comment]
My 2 cents:
* We should definitely use an existing authentication system, like the one django exposes.
   * Doing auth ourselves might give us more control, but no code is bug-free and having some well-tested system is vital in these security related parts.
* Let's first think about what use-cases our authentication solution should eventually solve. Here are some I thought of
   * Per-Person authentication with custom read permissions per group(/entity) or view. Ideally every user could have their own layout (note: for the future)
   * Per-API users/tokens with custom read/write permissions for service calls/entities. For example I don't want my GPS logger on my phone to have access to all my security webcams.
   * Ideally also groups with shared permissions for easy setup
* There are 3 layers that I see we could put authentication in: HTTP views, service calls and entities.
   * I agree we should go with HTTP views first;
   * with service calls+entities I'm not sure though. Do we want to have a user only access certain service calls or entities, or do we also want to specify *which services* can be called on *which entities*?
* Saving passwords: I'm not 100% sure we should move away from plaintext `api_password:` in the config. Sure, it's insecure but using some external storage like keyring would I think just confuse users starting out 
   * with external password storage now some information necessary for startup is no longer stored in the configuration.
   * Here I think Hass.io could really step in, since we have so much control over the system, we can also dictate how passwords are stored.
* about https: I personally think having Home Assistant supporting https itself is a huge hack and we should drop support for it. The chance that we mess https up somewhere is just much too high, especially when implementing things like HSTS.
   * → https+HSTS+letsencrypt+http2 all should be managed by a reverse proxy like nginx.

**Comment by JensTimmerman** [comment]
@OttoWinter instead of saving pw plain text you could save it hashed:

As an upgrade option you could add and use a new config option `api_password_hash` and save it like
`salt:hex_password`
```
def validate_password_hash(api_password_hash, password):
    """Test if password is valid based on a given password"""
    password_hash, salt = api_password_hash.split(':')
    hashed_pw = hashlib.pbkdf2_hmac('sha256', bytes(password, 'utf-8'), bytes(salt, 'utf-8'), 100000)
    hashed_pw = binascii.hexlify(hashed_pw)
    return hmac.compare_digest(hashed_pw, password_hash)
```

The remember option should then not store this hash or the plaintext password, but a timestamped proof of authentication, but this get's pretty technicall fast.

But in the long run it would probably make more sense to having an on boarding process where users and passwords stored hashed in a database next to tokens/sessionids using existing (or to be developed?) aiohttp middleware (see also things like https://aiohttp.readthedocs.io/en/stable/web_quickstart.html#user-sessions )

**Comment by balloob** [comment]
Yes, passwords will be stored hashed. The only reason we currently don't have it, is because we don't really have a security layer. That's what we're trying to establish here 😉 

Ideally, no configuration.yaml is involved for changing passwords. It's all done via the Frontend or CLI (via the same API as frontend). Just like when you setup a new computer, we ask for a username and password and make that the admin account. (this fits with my bigger plans of an onboarding wizard including discovery/config entries etc). Configuration.yaml can be used to configure auth systems and if a user wants, configure an auth system that is just a list of user/pass combo's.

We can't just copy paste the Django system and use it. We can use it as inspiration to see what kind of things we need to think of.

I would expect our auth system to be modeled after OAuth 2:

- Exchange username/password/TOTP for an access and refresh token.
- Tokens will have attached scopes that indicate which parts of Home Assistant are accessible.

Auth will live inside `homeassistant.auth.*`. Will be able to specify `REQUIREMENTS` just like components/scripts/platforms so they can pull in connectors for active directory or whatever crazy things. 

The only thing that we need to consider, is that if we allow authentication, we also need to think about registration. And if we do registration, we need user profile page to allow people to manage their password/totp (if allowed by authentication). All these things can however be postponed. We can literally have our first auth be a list of hardcoded user/pass combos

```yaml
homeassistant:
  auth:
    - platform: bla
      users:
        - username: balloob
          password: bla
```

**Comment by akatrevorjay** [comment]
@OttoWinter I absolutely agree with dropping SSL support in hass. I tried to ignore that it the options exist to begin with. Just run it with letsencrypt and nginx, agreed.

Also agree with everything else you said, for that matter, except for storing passwords plaintext, a hash is more appropriate.

**Comment by akatrevorjay** [comment]
Instead of modeled after oauth2, why not use oath2 @balloob ?
I'm pretty sure it supports everything we need, no?

**Comment by balloob** [comment]
Here is my proposal for an MVP for users and permissions. It's the bare minimum (but still big). 

https://docs.google.com/drawings/d/1ciudYSgf973T6Tx9DBp7g4KHtCB6wL7bVSV__xXfqr4/edit?usp=sharing

**Comment by fanthos** [comment]
I think HTTP should also have HMAC support, not sure how to use it with oauth.

**Comment by balloob** [comment]
Password hashing algorithms are the responsibility of the auth provider.

**Comment by armills** [comment]
Can we have the auth providers use some form of the config flow manager? That's already got support for user input, complex flows such as OAuth, 2FA, and even includes schema verions. Especially since this is net new, we can enforce they all use it from the beginning.

**Comment by balloob** [comment]
Yes, that is a great idea. We should do that.

**Comment by NovapaX** [comment]
Has there been thought about a 'recovery' path?
(I think a safe but accessible way of access recovery is necessary in the case of a Hass.io box)
Maybe some sort of recovery-token for the 'owner'-user a user can write down or store somewhere?

I recon that recovery could just be one of the `auth_providers` but still...

**Comment by balloob** [comment]
Making recovery an auth provider sounds like an excellent idea. I think that we might also provide some command line tools to wipe all users and create a new user.

**Comment by joydashy** [comment]
Very excited this will receive more love now balloob found a new home at Unifi!

PS. I also agree that HA should drop HTTPS support, leave that to Nginx. HA should not be directly exposed to the internet.

**Comment by balloob** [comment]
We're not going to drop HTTPS support.

**Comment by fanthos** [comment]
I think it should be great if HASS can act as OAuth provider.
Also, I think most HTTP API(except `/api/stream` and `/api/websockets/`) should change to "universal" API, it should accessible using WebSockets.

**Comment by madjam002** [comment]
@balloob Is there a reason why you wanted to go down the route of a custom auth provider API rather than using something like OpenID connect? It would then be possible to plug in custom auth providers without any code changes.

**Comment by balloob** [comment]
I did not consider OpenID connect because it didn't show up when I did my research. We ended up with OAuth 2 and cherry-picked the client ID approach from IndieAuth. Eventually we might explore adopting more from the indieauth spec.

**Comment by balloob** [comment]
That is possible with the current architecture. One problem we have with IndieAuth is that it requires domain names while we run mainly local, having only IP or hostnames. That's why we stuck with just taking the client ID approach from it.
