### ISSUE TITLE
Store supported_features in entity registry

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#173]
I think that we should consider storing supported_features in the entity registry. We fetch it when an entity is added to Home Assistant.

This will allow Google/Alexa to still sync these devices. Currently you need to make sure that ALL your devices are not "unavailable" or else they will not be discovered.

This also brings up the point that supported features should be static. We already have this, except for in the media player, which really needs a clean up.

**Comment by OttoWinter** [comment]
What will be with entities that are not in the entity registry? (there are a few, when unique UD is not possible) Will they simply not show up in GA/etc?

**Comment by balloob** [comment]
Oh, I wasn't suggesting to drop supported_features from the state! So that can still be used as a fallback.

**Comment by OttoWinter** [comment]
Ok then, next question: What happens when an integration has an upgrade that changes the supported features - or an existing entity gains a new one (for example MQTT discovery)? 

Will there be an upgrade mechanism for this static info? (I do realize that would make it un-static, just pointing out potential issues this might cause 😉  )

> We fetch it when an entity is added to Home Assistant.

Does this mean on the initial add (when entity reg entry is created) or each add on a HA reboot?

**Comment by balloob** [comment]
On each HA reboot, we do a get_or_create with the latest info, and if an entry exists, we update it. https://github.com/home-assistant/home-assistant/blob/f8921f84d7315511f73ae90fd4235fbc489f54a8/homeassistant/helpers/entity_registry.py#L118-L124

**Comment by MartinHjelmare** [comment]
We now store `capabilities` in the entity registry taken from the `capability_attributes` property of the Entity instance.
