### ISSUE TITLE
Template Component: Handling non-deterministic and frequently updating templates

### ISSUE THREAD

**Issue by Swamp-Ig** [home-assistant/architecture#206]
This issue came up while working on [#22587](/home-assistant/home-assistant/issues/22587)

Template sensors and their friends can have two situations that are problematic: they don't update enough, and they update too much.

#### Non-deterministic templates

If a template uses non-deterministic behaviour, which means calling `now()` or using the `random` filter, users have to set up polling for it, [as documented here](https://deploy-preview-9184--home-assistant-docs.netlify.com/components/binary_sensor.template/#working-without-entities).

The solution as documented works fairly well, although it does mean setting up other entities to provide the polling signal, plus if there's a few of them set up like this they're all going to end up polling simultaneously.

#### Throttling updates

If templates reference a lot of entities, they can potentially update with every state change in the system.

This was discussed here #85, and the solution was to disallow templates that couldn't figure out an entity list for sensor and binary_sensor templates. 

This is a bit of heavy-handed approach, it stops potentially useful templates like for example a sensor that counts the number of entities with low battery states. 

##### Default behaviour

Flag any templates that call `now` or `random` during the template calculation, and if they're present schedule minutely updates.

Put a cool-down on calculation of templates to once every 30 seconds, so if there's an update triggered within 30 seconds of the last update then wait until the full 30 seconds are up before re-rendering, and ignore any additional triggers in that time.

##### User customisation of the behaviour

Create `poll` and `limit` functions that flag that the template needs polling or limiting, and just return `True`. They can be used like this:

```
{{ limit(minutes=60) and 
states.sensor
    |selectattr('attributes.battery', 'lt', 10)
    |join(', ', attribute='entity_id') }}
```

This one will generate a list of entities with low batteries, with rate-limit of updates of the template to every 60 mins.

```
{% set p = poll(seconds=10) %}{{ ['one', 'two', 'three']|random }}
```

Output a different value from one, two, or three, updating every 10 seconds.

More interestingly, create a sensor that generates changing colours that can then be fed into another template (say for a light or something) depending on the time of day:

```
{% set hr = poll(hours=1) and now().hours %}
{% if hr > 8 and hr < 17 and poll(minutes=5) %}
{{ ['red', 'green']|random }}
{% else %}
dark_blue
{% endif %}
```

Because of the flow control here, between 08:00 and 17:00 the template updates every 5 mins, while overnight it updates every hour. These polls wouldn't fall on the hour, but would be based on whenever the last poll happened.

#### Discussion

There's some big advantages to having poll and limit functions, rather than specify the poll/limit times external to the template. The main one is that the poll/limit interval is declared right there in the template, so it can't be lost. 

If the timings are defined externally to the template, then every place where this is a possibility requires another one or two side-config keys to specify it. It's not going to be used that much either so it becomes a maintenance issue where it has to be specified in (when I counted) about 25 different places, and done consistently, and documented in all those places too.

It's probably less important, but being able to fine tune the poll/limit frequency depending on the situation also has it's advantages. 

This concept actually wouldn't be that difficult to implement alongside stuff already done for [#22587](/home-assistant/home-assistant/issues/22587). It does add some complexity however, although that's simple enough to encapsulate in two places.

**Comment by bdraco** [comment]
> #### Discussion
> There's some big advantages to having poll and limit functions, rather than specify the poll/limit times external to the template. The main one is that the poll/limit interval is declared right there in the template, so it can't be lost.
>

I think it is a fantastic solution to have the control in the template as it avoids the need to implement interfaces in all 5 places we use these to control the frequency and avoids the need to build additional systems to complement `async_track_template_result`.  👍 🥇 💯 🚀 

I'm thinking of implementing the `User customization of the behaviour` section as:

`limit` as `rate_limit`

and

`poll` as `scan_interval`

I'm not planning on implementing the `Default behavior` changes.

**Comment by bdraco** [comment]
Considerations:

`scan_interval(None)` - disables all updates except manual ones via update_entity
update_entity calls need to bypass the rate limit.

Maybe?

`rate_limit(None)` - removes a rate limit

**Comment by bdraco** [comment]
I'm implementing `rate_limit()` as a wrapper around `timedelta` for maximum flexibility which means `rate_limit(0)` will disable the limit.

**Comment by KevinCathcart** [comment]
Just some minor food for thought: What happens if you use these directives in places where templates logically should be rendered fresh each time, rather that watching for updates?

For example, if I use them in the message part of a notify service call action step, do they have any effect? If not, should they warn or error if used? If they do have some effect, are they going to cause confusing results?

**Comment by bdraco** [comment]
> Just some minor food for thought: What happens if you use these directives in places where templates logically should be rendered fresh each time, rather than watching for updates?
> 
> For example, if I use them in the message part of a notify service call action step, do they have any effect? If not, should they warn or error if used? If they do have some effect, are they going to cause confusing/unexpected results?

This only applies to the places where we track templates.  Currently that is

- bayesian (binary sensors)
- template (entities and triggers)
- universal (media players)
- websocket_api (dev tools and markdown cards)

Other places don't watch templates for changes and render them on demand.

**Comment by KevinCathcart** [comment]
Right, but if I were to stick these function calls in templates the other places, what happens? Do I get template compile errors (from the function not being defined in those cases)? Or do they compile and render successfully but effectively to have no impact at runtime? If this latter case, should they warn or error, since you are using them someplace where they make no sense? Or is it more important to ensure that a template can be copied and pasted from one of the tracked cases and used in one of the untracked cases without modifications?

Is there any chance that one of the existing (or some not yet added) non-tracked contexts could become a tracked context in the future? If so that might impact what the answers to the above should be. 

I'm only asking because I think it is worth having thought these sorts of things through fully, lest they have the potential to cause more headaches like the ones you have been spending so much time fixing recently.

**Comment by bdraco** [comment]
> Right, but if I were to stick these function calls in templates the other places, what happens? Do I get template compile errors (from the function not being defined in those cases)? Or do they compile and render successfully but effectively to have no impact at runtime? If this latter case, should they warn or error, since you are using them someplace where they make no sense? Or is it more important to ensure that a template can be copied and pasted from one of the tracked cases and used in one of the untracked cases without modifications?
> 
> Is there any chance that one of the existing (or some not yet added) non-tracked contexts could become a tracked context in the future? If so that might impact what the answers to the above should be.
> 
> I'm only asking because I think it is worth having thought these sorts of things through fully, lest they have the potential to cause more headaches like the ones you have been spending so much time fixing recently.

The same engine is used in all places so it doesn't matter what the content of the template is.  The only time we care about tracking it is when we want it to re-render on state changed events.

**Comment by tdejneka** [comment]
How does `scan_interval ` address the requirement to evaluate a template once, at the start of every new day?
This used to be easily achieved prior to recent changes (but no longer). As far as I know, `scan_interval` is not synced with the clock so that, for example, a 1-hour interval always occurs on the hour (12:00, 13:00, 14:00, etc) or a 1-day interval occurs at midnight every day.

**Comment by bdraco** [comment]
> How does `scan_interval ` address the requirement to evaluate a template once, at the start of every new day?
> 
> This used to be easily achieved prior to recent changes (but no longer). As far as I know, `scan_interval` is not synced with the clock so that, for example, a 1-hour interval always occurs on the hour (12:00, 13:00, 14:00, etc) or a 1-day interval occurs at midnight every day. 
> 
> 
If you need that level of control an automation to update it at specific times could be combined with a scan interval of None.

**Comment by Petro31** [comment]
Can't you just use as_local(states.sensor.date.last_updated).  That resolves once a day at midnight.

**Comment by tdejneka** [comment]
>That resolves once a day at midnight.

It won't prevent listeners from being assigned to all other identifiable entities in the template. That's why `scan_interval` is being suggested. If the option is specified, the template is evaluated periodically, according to `scan_intetval`, as opposed to when entities in the template change state.

**Comment by bdraco** [comment]
The current proposal for implementing `scan_interval`

> What was achievable _without_ an automation now requires an automation. That's loss of functionality and an increase in complexity.
> 

Can you provide a full example of how this was achieved previously?

**Comment by tdejneka** [comment]
I can but it requires that I mention something that caused me, in another thread, to be accused of harassment and threatened with banning my GitHub account.

I need an assurance that discussing it here is the appropriate venue and won't get me banned.

**Comment by Petro31** [comment]
It was achieved by using the entity_id field that was deprecated...  Quit being dramatic.  The example config was 

```
entity_id: sensor.date
```
and it would update every day at midnight.

**Comment by bdraco** [comment]
> ```
> entity_id: sensor.date
> ```

Thanks. The piece I'm missing is the actual sensor config where that would be used.

**Comment by bdraco** [comment]
> I can but it requires that I mention something...

The discussion of the removal of `entity_id` has merit but its unhelpful when an issue about `Template editor hangs Home Assistant` becomes a soapbox for the re-addition of `entity_id`.  

This issue is about `Handling non-deterministic and frequently updating templates` which is an appropriate venue to discuss solutions that move us closer to that goal.

**Comment by tdejneka** [comment]
> **soapbox** for the re-addition of entity_id

Instead of re-instating it, you appear to be committed to duplicating it using new options that still fall short. Can you help me understand this design decision?

**Comment by bdraco** [comment]
> > **soapbox** for the re-addition of entity_id
> 
> Instead of re-instating it, you appear to be committed to duplicating it using new options that still fall short. Can you help me understand this design decision?

The sticking point is that while it solves it for:

- template (entities)

It leaves us with a potentially different solution or implementing something similar for the other cases:

- bayesian (binary sensors)
- template (triggers)
- universal (media players)
- websocket_api (dev tools and markdown cards)

**Comment by tdejneka** [comment]
I see; you're attempting to normalize them.

It's a shame that until this normalization is eventually perfected, Template Sensors had to lose functionality immediately.

Now that I understand what else must be taken into consideration, how would the proposed inclusion of  `scan_interval` work with the others, such as Template Triggers? Or would `scan_intetval` be used exclusively with Template Sensors (just like the deprecated option).

**Comment by Petro31** [comment]
I believe the intention is that scan_interval would require a timedelta and it would be a line inside the template.

**Comment by KevinCathcart** [comment]
It might be possible to use a similar approach to allow for an entity_id alternative.

It should be possible to expose a function that from the template's perspective looks like it is defined as:
```python
def track(*entities: str, only: bool=False) -> bool:
   return True
```

It takes string arguments that are additional entities to track as though used by by the template itself. At the base level, this is a more ergonomic alternative to adding `set` directives whose variables are otherwise unused. It would be used like `{{ track('sensors.date') and ... }}`.

If the `only` keyword argument is passed as true, *only* the provided entities would be tracked, regardless of what entities are actually used in the rest of the template. This latter case is what enables this to work as a replacement for `entity_id`, while also working everywhere where tracked templates are used.

I pass no judgment on if this is worthwhile to implement, only that I think it is probably possible to implement, and that this is still orthogonal to the polling and rate limit options being implemented, except for a tiny bit of overlap in that `scan_interval(None)` and `track(only=True)` would be pretty much equivalent.

**Comment by tdejneka** [comment]
> it (`scan_interval`) would be a line inside the template

That sounds promising.

 Its presence in a template would cause no other listeners to be assigned? In other words, regardless whatever else is in the template (like `states`) it gets evaluated exclusively according to the `timedelta` specified by `scan_interval`.

If so, it restores most of the aforementioned lost functionality. It's a proposal I can support because it makes it easy, once again, to control/constrain the Template Sensor's evaluation.

**Comment by bdraco** [comment]
> It might be possible to use a similar approach to allow for an entity_id alternative.
> 

--------------------
Moving forward
--------------------
`{% rate_limit(minutes=1) and states | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}` 

Solves https://github.com/home-assistant/core/issues/40621 via https://github.com/home-assistant/core/pull/40667) 

--------------------
Undecided
--------------------
`{% track_states('sensor.time') and states | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}`. (proposed by @KevinCathcart)

OR

`{% scan_interval(minutes=1) and states | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}` (https://github.com/home-assistant/core/pull/40686)

OR

`{% scan_time_pattern(hours=*, minutes=5, seconds=0) and states | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}` (https://github.com/home-assistant/core/pull/40686)

**Comment by KevinCathcart** [comment]
All of those seem potentially workable.

In theory more than one could be implemented, although mutually exclusivly? (I had understood the polling nature of `scan_interval()` to be potentially in addition to the entity tracking rather than instead of, except of course in the scan_interval(None) case. But realistically, I suppose an instead-of implementation may be more useful.)

They do seem to cover different scenarios from each other, but some may not be worth the implementation cost. I'll reiterate that I'm indifferent to which one(s) are selected.

**Comment by bdraco** [comment]
The current favored approach is

`{% track_time_pattern(hours=*, minutes=5, seconds=0) and states | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | count }}`

with the default being `track_time_pattern(hours=*, minutes=*, seconds=0)` when there are no entities and either `now` or `utcnow` is present in the template.

with the option to turn off tracking `track_time_pattern(None)`

**Comment by bdraco** [comment]
In order to reduce the complexity and keep the code maintainable, I'm going to see about breaking all the listener management into a separate class.

**Comment by Mariusthvdb** [comment]
how would this translate in a template we only need to update on manual trigger (ie, doesn't update automatically)?
(or, for that matter,would only update upon clicking enter in the dev tools?

**Comment by bdraco** [comment]
> how would this translate in a template we only need to update on manual trigger (ie, doesn't update automatically)?
> (or, for that matter,would only update upon clicking enter in the dev tools?


This would disable all updates:
```{% track_time_pattern(None) and states | count %}```

**Comment by Mariusthvdb** [comment]
I see, thanks. would you consider adding `track_time_pattern('off')` to the configuration options? I mean actually setting something to 'off' is more clear than the 'None' we are used to for when something is not available or not configured ....?

**Comment by bdraco** [comment]
I'm not sure what the exact syntax will be yet as I'm hoping to reuse some of the schema from automations, but I'll see if I can get if it doesn't cause any fallout to automation triggers.

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/pull/41147 implements the remaining piece.

**Comment by bdraco** [comment]
Closing per https://github.com/home-assistant/core/pull/41147#issuecomment-703250497

**Comment by bdraco** [comment]
`track_time_pattern` isn't moving forward due to feature creep concerns.

If you need to disable automatic template updates, `{{ rate_limit(days=500000) }}` can accomplish almost the same thing (just a tad bit less efficient) and an automation that calls `homeassistant.update_entity` https://www.home-assistant.io/docs/scripts/service-calls/#homeassistant-services

**Comment by tdejneka** [comment]
Will this update once a day _at the beginning of the day_? In other words, is it a substitute for `entity_id: sensor.date`?
```
{{ rate_limit(days=1) }}
```

Or will it update once a day but at an indeterminate time during the day? (i.e. intervals are based on the last restart time)

**Comment by bdraco** [comment]
> Will this update once a day _at the beginning of the day_? In other words, is it a substitute for `entity_id: sensor.date`?
> 
> ```
> {{ rate_limit(days=1) }}
> ```
> 
> Or will it update once a day but at an indeterminate time during the day? (i.e. intervals are based on the last restart time)
> 
> The ability to (conveniently) refresh a Template Sensor daily, at the _start_ of every new day, is a common need.

No, it won't be a good substitute for it.  Rate limit only limits, it does not give manual control over them.

**Comment by bdraco** [comment]
We are going to defer shipping the `rate_limit()` template directive in 0.116. Research is ongoing for a better solution.

**Comment by Mariusthvdb** [comment]
would it in any way be acceptable to at least consider re-instating the `entity_id:` which gave us both: control over update_frequency, and control over limiting listeners? Don't want to get slammed over this, so I'll be short and quick, but that would seem the ideal world: 

fantastic automatic state indentification (115 _brought_ us) and manual control (115 _took from_ us).

I am aware you're also looking beyond the template sensor domain, still, this is the main field it now is bothering HA, and the topic of this thread.

Anyways, thanks for considering.
