### ISSUE TITLE
split devices / config entries override area of device

### ISSUE THREAD

**Issue by vigonotion** [home-assistant/architecture#212]
The problem with the current implementation:

I have a Sonoff 4ch relay (4 switches) in the cellar. This one controls a lamp in the hall and a lamp in the garden.

I can only add the device to one area, but those switches should be in different areas. Therefore I can not turn off the garden (via area) without turning off the hall.

My idea is to add the ability to add a virtual device which splits a device into logical sub-devices, which can then be placed into areas. Another idea would be to allow switches/sensors etc to override the area.

Some other scenarios where this could happen:
- esp32 controlling wired window contacts in the whole house
- every other controller which controls sensors/switches in the whole house

**Comment by andriej** [comment]
I have the same "issue" with my arduino mega - it's in garage, but controlling all lights in house. 
I'm able to reprogram it with autodiscovery and locations, but won't be able to assign each light to each area. 

It's not something that I can't live without, but seeing this rised - just my 0.02€

**Comment by balloob** [comment]
Virtual device already exists: https://www.home-assistant.io/components/light.switch/

**Comment by vigonotion** [comment]
This doesn't solve the issue. Maybe the "virtual device" was confusing.

Some sensors/lights/switches etc. need to be in another area than the device is

**Comment by balloob** [comment]
What other category would a sensor be in? Since it has no controls, no other category would fit. Unless it's binary sensor but in that case it's a bug, and the integration should be fixed.

**Comment by dgomes** [comment]
I have a single controller that does all my covers centrally (this is quite common)

**Comment by vigonotion** [comment]
Example:
Device has 4 relays to control 4 switches
Switch 1: a light in the garden (area: garden)
Switch 2: a light in the hall (area: hall)
Switch 3: a light in the cellar (area: cellar)
...

But I can only put the device in one area, for example into the cellar.

**Comment by balloob** [comment]
Oh, my bad. Until I read the last 2 comments I somehow thought you meant entities, not devices.

**Comment by Swamp-Ig** [comment]
I have the same issue. I have a few "multi-headed" devices with outputs in different areas.

**Comment by asherw** [comment]
Hi,
Have the same issue with Aeotec Dual Nano zwave switches.
https://aeotec.com/z-wave-outlet-socket

**Comment by Swamp-Ig** [comment]
So to fix this properly we need some idea of what constitutes a device, and what's an endpoint.

Working definition:

Device: Something with it's own power supply
Endpoint: Grouping of geographical outputs from a single device.

So for example the z-wave dual switch might have different endpoints in different rooms, each with their own power consumption, switch state, etc.

Endpoints can end up in the same area, but sometimes they don't, therefore it should be possible to put different endpoints in different areas.

I think that really it is up to the integration to decide what constitutes an endpoint, if we leave this configurable it will get too messy. There's the potential to have a template device, that groups multiple template sensors / switches etc, but that's out of scope for this issue.

#### Option 1: Each endpoint is its own device

This is pretty simple to implement, just register a different identifier in the device registry for each endpoint. They stop being associated with each other.

I've implemented this for z-wave devices already in [the PR here](https://github.com/home-assistant/home-assistant/pull/24032/files#diff-34736f9c4da86b6334cf5d201370707fR1041)

Basically the device ID goes from:

```python
( 'zwave', 34 )
```

to:
```python
( 'zwave', "34_2" )
```

The first endpoint doesn't change from the integer version in this PR, this ensures that the old devices aren't orphaned and end up with no entities associated.

#### Option 2: Have some concept of endpoints as well as devices

I think the cleanest way to do this one is to allow device IDs to be a 3-tuple:

```python
( 'zwave', 34, 2 )
```

This almost works currently, it doesn't persist and load back cleanly however since when it loads it comes out as a list not a tuple, but that's easy enough to fix.

You'd probably also link back to the parent device somehow, probably with a different attribute.

```python
    @property
    def device_info(self):
        """Return device information."""
        return {
            'identifiers': {
                (DOMAIN, self.node_id, self.values.primary.instance)
            },
            'parent': {
                (DOMAIN, self.node_id)
            },
            'manufacturer': self.node.manufacturer_name,
            'model': self.node.product_name,
            'name': "{} ({})".format(node_name(self.node), self.values.primary.instance),
        }
```

This approach still means the device_state_attributes are kept separate for each endpoint, which is probably what we want anyhow. The parent identifier is basically just there for UI purposes so they can get grouped together. The parent device can have its own device state attributes if desired, and if some entity is attached to it directly.

**Comment by elupus** [comment]
Well for knx this doesn't work so well. You technically can't attribute a physical device to a endpoint.
You really only have a controlling address (multiple addresses can control same endpoint, one address can control multiple endpoints). Addresses are created by electrician at install.
It's more like a mqtt topic that has no relationship to the physical controlling device. With one topic for setting and one for reading state.

**Comment by Swamp-Ig** [comment]
How do you group any part of the integration into a device/endpoint then? Is the whole integration all one big device? Would this be best configured in the knx integration, rather than push it up a level?

**Comment by elupus** [comment]
Yeah well this the issue with knx currently it has no globally unique ID for entities nor a way to group entities into devices based on any automatic detection.

It technically doesn't even care for the concept of devices. It's just control points linked to control points. Ie when you provision the system you link the sending control of a wall button to the receiving control of a actuator by an arbitrarily invented address which is local to this system.

In home assistant we model it by a light entity with configured addresses for setting and reading state. https://www.home-assistant.io/components/light.knx/

Given above limitations I suppose the concept of the device registry gets a bit muddy, while entities work fine.

It would be possible to manually model devices in configuration. Will be a lot of work, but can be done. Just let user enter some GUID to keep it unique.

Back to topic..
I think the concept of device should stay linked to the actuator, not the controlled thing. If we start creating separate devices for each light, switch, sensor it's no different from the entities themself. So the concept of area assignable endpoints on a device (is similar to 2) would the be most logical.

Option 3:
Let areas be assigned to each entity instead of device ( potentially inherited from device )

**Comment by Swamp-Ig** [comment]
Option 3 was deliberately not adopted since it adds too much complexity for the usual case which is a device with multiple entities which are attached together and respond together.

> Given above limitations I suppose the concept of the device registry gets a bit muddy, while entities work fine.

It would seem to me that the default for KNX then is to have an endpoint / device per entity (address), which does give you the flexibility to assign them anywhere. You might then configure some of these to get grouped into a single device, but there's really no option but to do that manually. You don't need to use a GUID, it's just a matter of coming up with some (opaque to HA) identifier per endpoint. HA does the GUID part. Any string is perfectly fine. 

The default can be device per entity, it's only when we have this information that entities are grouped then the integration can use it (or configure it), but that's really up to the integration.

**Comment by Swamp-Ig** [comment]
Had a quick look at the knx integration. It really looks like this should be device-per-entity to me. The device ID would probably be the address by the looks of it. 

A device would be a logical grouping on entities where they're all part of the same "thing", for example the zwave switch exposes the current, voltage, total energy use, alarm states, etc all as different entities grouped into one device. The sensors will have temp, pressure, UV level, humidity, etc all as different entities in the device.

Some z-wave devices have more than one output, so they can switch more than one state in one physical device. In this case each switch would be a sub-device (which really is just a device anyhow, only really a sub-device for UI purposes).

**Comment by Swamp-Ig** [comment]
Proposal:

1. Device info is allowed to return a 3-tuple instead of a 2-tuple.
2. It can also return a `parent_id` which can either be a (integration dependent) opaque ID as passed by the above, or it can be a device UID.

```python
 @property
    def device_info(self):
        """Return device information."""
        return {
            'identifiers': {
                (DOMAIN, self.node_id, self.values.primary.instance)
            },
            'parent_id': {
                (DOMAIN, self.node_id)
            },
        }
```

3. The device panel on the integration config window gets sub-devices within the device, probably with a level 2 heading, area name, icon to edit the area and name, and associated devices. Can mock this up but it's probably as easy just to do it and see what it looks like.

If this sounds good I can implement it tomorrow.

**Comment by Swamp-Ig** [comment]
Oh and I guess:

Define "device" as a group of entities that have a power supply, and sub-device as a group of entities that live in one geographical location.

**Comment by vigonotion** [comment]
I like that, but I think we should not call it "sub-device", that is not self explanatory and most times not fitting. I liked "endpoint" though

**Comment by Jc2k** [comment]
I've just recently added support for device info to homekit_controller (https://github.com/home-assistant/home-assistant/pull/23874/files) and it seemed relevant here.

A homekit endpoint exposes multiple accessories, and each accessory is composed of one or more services. An accessory is a physical thing and can be placed in an area. The services tend to map to HA entities. So the API exposes the sort of structure I think you are describing here (I can group entities together by device, and link them to a parent device (hub)). It can get a little fun though - a homekit device can:

 * Have a hub that has no services of its own. So there is a parent device with no entities and multiple child devices. Each child device has 1 or more entities.
 * Have no hub. E.g a light strip. It's just a single device and a single entity.
 * Have a hub that has its own entities and multiple devices with their own entities
 * And annoyingly, there are some hubs that don't make use of the 'accessory' mechanism and put all the services under one root accessory. So right now they are grouped as a single device and theres no way to ungroup them. There's not much I can do here short of having a "quirks" database that kicks in for blacklisted hubs and forces each entity into its own device.

Right now I handle the first 3 cases automatically using the existing code (each "Accessory" on a hub gets its own device, connected to a parent hub if there is a hub), and there is no way to automatically handle the 4th. Does this proposal change anything for me?

I think you can already return 3-tuples for `identifiers` - isn't it just an opaque identifier?

How does this related to the `via_hub` mechanism? Does it replace it? Doesn't this allow you to create multiple devices and link them back to a parent device?

**Comment by balloob** [comment]
How is this different from the `via_hub` property? https://developers.home-assistant.io/docs/en/device_registry_index.html#device-properties

**Comment by Swamp-Ig** [comment]
> I think you can already return 3-tuples for identifiers - isn't it just an opaque identifier?

It doesn't persist and load properly, since it saves as an array which isn't hashable when it gets reloaded. It's a pretty minor bug and easy to fix.

> How is this different from the via_hub property?

According to the docs, a hub is:

> "Identifier of a device that routes messages between this device and Home Assistant. Examples of such devices are hubs. This is used to show device topology in Home Assistant."

This is different to a device, which is roughly:

> A network connected thing that has an independent power supply, and which may connect to a hub.

And an endpoint:

> A collection of entities connected to a device that is in a particular geographic area (room). This is part of an overall device, and would likely not have a separate network address.

What these levels actually represent is really up to the integration to define really. Previously however we've enforced that a device is only in one area, whereas splitting out into endpoints allows this abstraction to be broken. There's still going to be integrations where every entity is its own device, and that's what KNX will look like. Z-Wave devices would have all three levels, with the hub being the z-wave stick. Central HVAC systems often have zones, they would likely be endpoints rather than devices. 

Really there's no *functional* reason why you even need to have the hub/parent device levels, they're really there for UI purposes. You could just merge the device and endpoint together and declare a device is always in one geographical area.

That's a quick image mock-up of what it would look like in the integrations config window:

![Multi Endpoint](https://user-images.githubusercontent.com/6317645/58521594-aa8c5080-81ef-11e9-9b26-18f90eb5f4cf.png)

**Comment by Jc2k** [comment]
I use 3-tuples in device info on dev, if there is a bug i'd like to try and fix it. Tuples of strings are hashable, so do you mean there is a bug unserializing from JSON (as i guess it will come back as a list rather than a tuple). But I think there is code to handle [that](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/helpers/device_registry.py#L242)?

Here is what one of my examples looks like on `dev`, there is no unmerged code here. `HomeW` is a 'hub', the other devices are connected over a radio signal (dont know what kind). There is one "config entry". There is one homekit pairing, to a thermostate which also acts as a hub. So there are 4 physical devices that need to have assignable locations. The integration has made 4 devices for that config entry, and 3 of them use `HomeW` as their parent (`via_hub`).

<img width="1171" alt="Screenshot 2019-05-29 at 09 07 23" src="https://user-images.githubusercontent.com/11544/58540506-6a2dd200-81f1-11e9-9dbc-3494910b3ccd.png">

They can each have their own areas.

This works if the hub has no children and it works if the hub has no entities of its own.

I'm not sure what the `parent` field adds right now. It looks like functionally its the same as `via_hub` but it has different terminology. Does the documentation around `via_hub` need improving? Does the name `via_hub` imply something it shouldn't? Have we conflated multiple different concepts into `via_hub`?

**Comment by Swamp-Ig** [comment]
So, the device I'm using is a double light switch, it connects over radio to a hub, but switches two different lights. In my setup there's one inside and one outside, clearly in different areas.

Each of the endpoints can be a separate device so they can be assigned different areas, that's what the linked PR from above does, but what is their hub? Is it ok to have sub-hubs? Should area get inherited, and when should this happen?

I'm not particularly wedded to the parent device concept, but if not then really we are forced to define a device as a set of related entities that reside in a particular area. As long as we have that definition then

**Comment by balloob** [comment]
I think it's fine to have chained via_hubs. In the end it's just a graph with nodes being connected to HA either directly or via 1 or more devices. I think that if a device has instances, we should create one device entry for the main device, and then one device for each instance.

**Comment by Swamp-Ig** [comment]
In which case we should update the definition of hub. I will fix up that zwave PR to align with this decision and submit a doc patch. Do you want to assign this issue to me @balloob ?

**Comment by Swamp-Ig** [comment]
I kinda wonder if hub should be renamed parent too, since with this definition it's not a hub really.

**Comment by balloob** [comment]
well that would be a breaking change, however, since we currently don't allow external integrations to use device info, you should be able to find all occurrences in our codebase and update it. Should also update the data when loading the device registry.

Would parent or `via_device` be better?

**Comment by Swamp-Ig** [comment]
Yes, I agree. It's a breaking change but not one that's really going to break that much at the moment. 

The main change really is fixing existing integrations that don't quite use the right abstraction for devices and end up with devices that contain too much or too little. The UPnP/IGD integration for example puts all the readings from my network gateway in different devices, when they're not. The sonoff device that kicked this whole issue off is overly inclusive and puts too much in one device.

`via_device` is sensible.

**Comment by vigonotion** [comment]
#272 does not solve the issue, it is only one part of it.
The renaming of via_hub to via_device opens the possibility to solve this issue, which is to actually split the device into "sub-devices" which use via_device.

Therefore this issue is not yet solved. Should it be re-opened or should I create a new issue for that?

**Comment by Jc2k** [comment]
Do you mean that we need a bunch of PRs to actually covert more integrations to use via_device or that there is something architecturally missing from via_device?

**Comment by Swamp-Ig** [comment]
Each integration needs to sort out how they want to split the devices, this isn't an overall architecture issue anymore the architecture issue is solved.

Some integrations have too little in each device, splitting every measurement into a different device, while others have too much in each device. It's up to the integrations to figure it out, and there's going to be different answers for each integration.

I have got it fixed now for z-wave at least, which prompted quite a few people to find this issue.
