### ISSUE TITLE
Be able to choose temperature device on a climate device

### ISSUE THREAD

**Issue by alekslyse** [home-assistant/architecture#226]
This is a suggestion after some discussion on discord, regarding an ongoing issue, originally thought to be an OZW bug, where units like HeatIT Thermofloor (zwave) get included, but correct temperature is not shown.

The issue is this, when a zwave device is exposing more than one temperature sensor it generate one entity pr sensor, HA chooses the first and uses the rest as generic temperature sensors. 

This is a behavour that break the implementation, as if for example I want to use the floor sensor I have to change the zwave config file to make that the first one.

Suggestion: If more than one entity of the same type is found on a climate device, be able to choose which one to use as primary.

Some reference material: https://community.home-assistant.io/t/unable-to-get-current-temperature-from-heatit-z-wave-thermostat/90758/8

**Comment by Swamp-Ig** [comment]
Would this work well as a template climate device? Then you can use anything as the temp source.

**Comment by alekslyse** [comment]
> Would this work well as a template climate device? Then you can use anything as the temp source.

It probably could, but since this is a zwave device that expose several temperature sensors it should be important to be able to assign device to sensors. From the discussion on discord this seem like the best solution as OZW so and will expose multiple sensors, but not being able to choose which one to use on the main device (zwave device)

**Comment by alekslyse** [comment]
We are talking about sensors exposed by the device itself, not using another zwave or sensor that is not builtin. the three sensors im talking about is exposed by the one device.

This would also regard for example a HVAC that have one internal and one external temperature sensor. A user should be able to assign which one to use as the assignment.

Today to solve this you have to open the xml-file that is related to zwave and manually set the primary sensor

**Comment by Swamp-Ig** [comment]
So it's a zwave climate device issue then, not a general climate device issue? Are there any other devices with this problem?

**Comment by alekslyse** [comment]
I personally dont have any other devices that expose multiple temperature sensors, but from discussing it with the OZW maintainer on discord the problem is zwave have no idea what sensors to use. 

I would assume this problem would be present for all units that expose multiple entities of the same type, where ha need to guess what entity to use as primary one

**Comment by Swamp-Ig** [comment]
I did look at most of the climate devices as part of the great migration. I can't remember any that did this, but I wasn't really looking specifically.

Maybe take a look through the code? If it's just a z wave thing then that's probably the place to fix it, in the zw settings. Otherwise for more of a general approach it probably going to be a template device I think, since otherwise it ends up in every climate integration and those are messy enough already :grin:

**Comment by awarecan** [comment]
Nest support multiple temperature sensor, but did not opened that API, and won't open it as the whole API is sunset now.

====

In HA, we stored the order of configuration item from yaml file, so the first item in the list would be the primary one.

**Comment by MartinHjelmare** [comment]
If we're going to do another change of the climate model it'll be to remove the current temperature from it and just expose those measurements as separate sensor entities. That's what we do now for other new entity models, eg humidifier. 

Let's close here since the suggestion isn't the correct foundation for a solution.
