### ISSUE TITLE
Don't update 'last_changed' on restart

### ISSUE THREAD

**Issue by SaturnusDJ** [home-assistant/architecture#230]
Searched for a topic about this in this repo and https://github.com/home-assistant/home-assistant.io but surprisingly, none found. https://github.com/home-assistant/architecture/issues/190 is related though.

Mains:
https://community.home-assistant.io/t/a-state-timestamp-that-is-not-affected-by-ha-restarts/115822
https://community.home-assistant.io/t/last-changed-last-updated/14023
https://community.home-assistant.io/t/real-state-last-changed/15928

Some related, some other area:
https://community.home-assistant.io/t/state-restoration/47850
https://community.home-assistant.io/t/sensor-states-across-restarts/94841
https://community.home-assistant.io/t/saving-input-boolean-states-between-restarts/53035
https://www.reddit.com/r/homeassistant/comments/aiscf4/nodered_restore_state_of_home_assistant_after/
https://github.com/dale3h/homeassistant-config/blob/master/packages/drop-in/persistence.yaml
https://github.com/gazoscalvertos/HASS-Persistence
http://blog.deadlypenguin.com/blog/2018/11/28/away-time-home-assistant/

(Suggesting not to cherry pick from the above.)

In the 2nd, the admin says:
> It’s not possible. Last updated and last changed are maintained by the state machine and not the entity.
>
>Also, restarting Home Assistant is not a common thing so I wouldn’t worry about it
1. Unclear why that would make it impossible. Sure there will be at least a workaround possible.
2. a. Sometimes when people say that they wish HA to be more stable and predictable, the counter argument is that it is still in development and you should see it as beta software. Then also admit that that means a lot of restarts to add components to your configuration, update the version, fix breaking changes, etc.
b. Often the configuration needs to be adjusted. Home automation is a very creative process which means new ideas come up regularly. Thus restarts.
c. Quite some functions are not well documented, resulting in trial and error, contributing to lots of restarts to get something a bit more advanced working.

"Restarting HA is not a common thing" is not true.

Why reported as an issue?
Because what is happening now is plain wrong from use case perspective. It is a fundamental flaw. HA restarts, next thing you know all entities are saying to have been updated/changed at that timestamp.

Alarm disarmed 1 minute ago.
Panic button 1 minute ago.
Motion detection clear 1 minute ago.
Mailbox count 3 1 minute ago.
Door closed 1 minute ago.
Cat litterbox used 1 minute ago.
Person x home 1 minute ago.
Person y away 1 minute ago.
Light hallway 1 minute ago.
Telegrambot used 1 minute ago.

Very informative. 😐

Basic reliability and truthfulness of information is being compromised.

Solutions?
- Don't update last_changed and/or last_updated on restarts.
- Introduce a new attribute timestamp that doesn't update on HA restarts.

**Comment by cgarwood** [comment]
I think updated last_updated on restarts makes sense, assuming it's getting fresh data from the device. To me `last_updated` means "this is the time that I got data from the device" even if the data is the same as previously.

I would agree though that `last_changed` shouldn't update unless the data is actually different.

**Comment by andriej** [comment]
If I could add my two cents, right now it's almost last thing missing for me personally. 
+1 for the idea of not updating last_changed and presenting it in UI (or introducing timestamp for that?)

**Comment by Adminiuga** [comment]
https://github.com/home-assistant/architecture/issues/230#issuecomment-491319065
I agree on both points

**Comment by dgomes** [comment]
I think everyone agrees with the https://github.com/home-assistant/architecture/issues/230#issuecomment-491319065

This is not an architecture issue but a bug or "implementation issue", I face this with MQTT sensors because when HA boots it gets "new values" which are actually old values (values that are retained in the MQTT broker)

**Comment by SaturnusDJ** [comment]
> 
> 
> I think updated last_updated on restarts makes sense, assuming it's getting fresh data from the device. To me `last_updated` means "this is the time that I got data from the device" even if the data is the same as previously.
> 
> I would agree though that `last_changed` shouldn't update unless the data is actually different.
Makes sense.
Note that there are quite some cases in which updates get pushed to HA from other devices at irregular intervals, often not exactly on HA startup. Thus even then the new data isn't so fresh. Doesn't bother me though as long as there is at least one time attribute that is not reset on HA startup.

**Comment by Swamp-Ig** [comment]
Last changed is a bit tricky though, for example z wave devices are in an unknown state on startup, and can take a bit of time to refresh.

I'm not sure the state is saved, but let's pretend it is since I'm sure there's something else similar.

Do we update the last changed when it finally does refresh, or not? It has changed - from unknown to known, but it's only our knowledge of the state and not the state itself.

**Comment by Adminiuga** [comment]
> Do we update the last changed when it finally does refresh, or not? It has changed - from unknown to known, but it's only our knowledge of the state and not the state itself.

I see your point, is state transition from `unavailable` to some new state counts as `last_changed` event?
I'd say unless the state was `unavailable` prior the restart, then after the restart "last_changed" is the same as it was prior the restart, until we successfully poll the device (which updates `last_updated`) and possible `last_changed` if polled state != current state.

**Comment by Swamp-Ig** [comment]
Currently state objects are either in the state machine, or they're not. There's not really a concept of a state that's 'loading', so this means that when the state is actually loaded the `EVENT_STATE_CHANGED` event gets sent out, with `None` as the old state, regardless of if it existed in the state machine before in a previous run.

There's various ways of dealing with persistence. Some entities inherit from `RestoreEntity`, in which case their state is stored to and retrieved from disk which can be pulled in by the entity when it's set up, and then saved to the state machine. Z-Wave devices will pull state from the device itself and then call (eventually) `async_set_state` for the first time when the state is eventually retrieved.

AFAICS really what you want is for an entity that, by some mechanism, restores its state somehow is to tell the state machine that the state is currently loading, and then for the first `async_set_state` call after this, instead of an `EVENT_STATE_CHANGED` event, the state machine sends out an `EVENT_STATE_LOADED` event where only the new state is provided.

Another possibility would be to just change the data in the state changed event to indicate this is a loading event and that the previous state isn't actually `None`, but rather it was unknown. You'd also not bump the last_changed time (probably set it in the `async_loading_state` call?).

I hope that makes sense. Here's a table to summarise:

 Lifecycle | Event | `old_state` | `new_state` | last_changed
-----------|-----|-----|------|--
`async_set_state` (creating entity) | state_changed | None | state | now
`async_set_state` (existing) | state_changed | old | new | now (if state change or forced)
`async_remove` | state_changed | old | None | now
`async_loading` | maybe send a state_loading event | | | 
`async_set_state` (after above) | state_loaded | | new | now
`async_set_state` (alternative) | state_changed | a special singleton loading state with state.state == 'unknown'  | new | last_change or `None`

The last row probably really makes more sense, since then when the front end or whatever queries the state machine it's clear that the state is unknown and it stays pretty consistent with what's currently there.

**Comment by boojew** [comment]
If I understand correctly, then yes I agree with this. Storing/fetching the state off disk for "last_changed" makes perfect sense.

**Comment by SaturnusDJ** [comment]
Any progress?

If I could, I would work on this, but currently I am still a programming noob.

**Comment by SaturnusDJ** [comment]
Bump.

**Comment by Torrentus** [comment]
Also experiencing this as a problem and would love to be able to get the actual last_change rather then the last_restart ;-)

**Comment by azogue** [comment]
I've also internally complained about this sometimes, and IMHO it should be fixed for all **`RestoreEntity`** items, as we have a perfect photo of their states, but we are discarding some of their properties.

Now, each integration decides what to do with the restored state on HA start, but because how the set_state & state_changed event infrastructure is implemented, **the first set_state always resets the `last_changed` attribute**, as it is getting the `old_state = self._states.get(entity_id)` to compare with.

A quick and simple solution for ALL the integrations using `RestoreEntity` would be to **directly write the restored state in the `StateMachine` when calling `async_get_last_state`**. 

That way, if the integration does nothing else, and just sets the state, the 1st state update would have an `old_state` to compare with, and `last_changed` is preserved.
In this scenario, if the entity setup stage does not change anything (state and attributes), then even the state_changed event is avoided.

The changes to implement this behavior would be something like this:

```python
# In helpers/restore_state.py
class RestoreEntity(Entity):

    async def async_get_last_state(self) -> Optional[State]:
        """Get the entity state from the previous run."""
        if self.hass is None or self.entity_id is None:
            # Return None if this entity isn't added to hass yet
            _LOGGER.warning("Cannot get last state. Entity not added to hass")
            return None
        data = await RestoreStateData.async_get_instance(self.hass)
        if self.entity_id not in data.last_states:
            return None

        restored_state = data.last_states[self.entity_id].state
        # Direct write in state machine
        self.hass.states.async_restore(self.entity_id, restored_state)
        return restored_state

# In core.py
class StateMachine:

    @callback
    def async_restore(
        self,
        entity_id: str,
        restored_state: State,
    ) -> None:
        """Restore the last state of an entity.

        This method must be run in the event loop.
        """
        assert entity_id not in self._states
        self._states[entity_id] = restored_state
```

**Comment by cmatte** [comment]
Is there any development on this?

**Comment by azogue** [comment]
> Is there any development on this?

I'm working with the change I suggested above for some weeks now, and it works as expected for any entity based on `RestoreEntity`, with no collateral, but I don't know if that approach would be liked, as it is messing around with the `StateMachine`.

But the change has meaning, for me at least. State restoration is _exactly_ that: recover the old state as it was in the state machine. If in `added_to_hass` the new state changes, then a STATE_CHANGED event would fire. If not, the setup goes silent and no event is fired (because there is no change!).

I think that approach is a better one for the context we have now with the integrations and setup from UI, because we don't have a real "HA start" period anymore, as integrations are added and removed in the same HA session.

Anyway, the lack of comments here doesn't help :)

**Comment by orson1282** [comment]
Just adding my thoughts to this, making a case for **not** updating the last_changed on hass restart.

So I have a sensor on battery that wakes up from sleep every 3 hours and reports its state to MQTT.
It was all fine, until I restarted hass and the last_updated value was wrong.

Thanks @azogue  for working on this issue. 👍

**Comment by kalmanoharan** [comment]
Thanks guys for working on this issue. Its most needed feature by many HA users 👍

**Comment by SaturnusDJ** [comment]
@azogue 
How is it going now?
If you would like me to test something, let me know. Preferably on a selective few sensors first, but if not possible, for the sake of getting this awful architectural design flaw out the way, then just system wide.

**Comment by azogue** [comment]
> @azogue
> How is it going now?
> If you would like me to test something, let me know. Preferably on a selective few sensors first, but if not possible, for the sake of getting this awful architectural design flaw out the way, then just system wide.

Hi @SaturnusDJ,

The change I proposed is on the core level, so it affects all entities based on `RestoreEntity` (not exactly system-wide, but applies to lots of integrations). 
You're free to do the changes in `core.py` and `helpers/restore_state.py` and try it for yourself (it works as expected).

When I said 
> I'm working with the change I suggested above for some weeks now

I meant I'm **using** that exact code changes, there is nothing more to test or change, but as these changes are not on some component (which could be copied & modified in `custom_components`), I have to modify the code manually after any HA Core update, so it's kind of uncomfortable to do it once per week :)

**I could do a PR** with that change (only needs to slightly modify some unit tests), but I wanted to discuss it first here, as I think it could be seen _controvertial_ at least, I was hoping to see more core maintainers around here to discuss different approaches :(

As this issue is now > 1 year old, and no core members have participated for a year, I think is time to cc some of them, even when it's not very polite to do it, sorry @balloob @frenck :)

**Comment by SaturnusDJ** [comment]
I am running the code now. For `helpers/restore_state.py` I commented out the last line, then inserted the new part of the code. For `core.py` it was inserted in the _StateMachine_ class, position does not matter right? This is correct?

**Comment by azogue** [comment]
> I am running the code now. For `helpers/restore_state.py` I commented out the last line, then inserted the new part of the code. For `core.py` it was inserted in the _StateMachine_ class, position does not matter right? This is correct?

Yes. Have you tried it? It should work on all integrations with devices inheriting from `RestoreEntity`, like **automations**

**Comment by SaturnusDJ** [comment]
It seems to work partly. That is I guess what you mean with 'inheriting from RestoreEntity.'

For example what I see:
Automations, alarm, persons, input_*s and counters keep their time.
Device trackers, lights, binary sensors, sensors, groups, switches get the HA restart time.

**Comment by azogue** [comment]
> For example what I see:
> Automations, alarm, persons, input_*s and counters keep their time.
> Device trackers, lights, binary sensors, sensors, groups, switches get the HA restart time.

It depends on each integration, there are sensors or binary sensors that work, and there are others that do not :(, but the `RestoreEntity` data is the only state information that gets stored on disk, so it can persist on restarts, in the JSON file on **`config/.storage/core.restore_state`**, so there are not so many possible approaches here. 

It's a good mechanism, but right now it's discarding the `last_changed` data, as it is creating entirely new states when called, that's what I wanted to approach. For the "generic" case you cannot get a good solution, IMO, as a behavior like this could be totally undesired for the entities of some integrations.

Also, the issue title could be misleading for others: I think we should address the **`last_changed` attribute persistence**, not the `last_updated`, as that one is perfectly consistent :)

**Comment by SaturnusDJ** [comment]
It is a good step. Thanks. 👌 

For more we have to wait for the devs right?

**Comment by SaturnusDJ** [comment]
@azogue 
I ran into a strange problem. I moved a light from Hue Hub to Zigbee2MQTT, keeping the name. It then became kind of defective. Switching it on only sent the on command, the switch flipped back to off quickly, so no correct on/off status. After wiping it from `core.restore_state` the light would work as expected *until* a restart, from there it was defective again. Spawning a new Docker container without the `helpers/restore_state.py` and `core.py` mods resulted in the light always working correctly. I then applied the mods again, and the light state became defective again.

**Comment by Sjorsa** [comment]
Is there any update on this? I've been running into this for a while also now.

**Comment by codingcatgirl** [comment]
I hope this can be implemented soon. The current behavior makes the property virtually useless for many usecases and is really unintuitive.

**Comment by SaturnusDJ** [comment]
Nothing will happen until one of the big boys agrees with this I guess.

**Comment by sanderlv** [comment]
Yes please!!!

**Comment by Santobert** [comment]
I too would be happy to see this implemented. However, this is not a repository for feature requests, but a place to discuss architectural changes that someone is already willing to implement. There seems to be some level of interest in your proposal, although there are still some open issues to discuss. If there is agreement at some point in the future, go ahead and prepare a PR to the codebase.

**Comment by frenck** [comment]
@SaturnusDJ what is your implementation proposal? As that is missing in the openings post imho.

For example, how to handle this consistently, where should this take place? How to handle integrations that are late, and supply their data after Home Assistant start has passed?

**Comment by thewindev** [comment]
@frenck a basic implementation would be to update last_changed ONLY when the state changes.
So when you restart HA, you currently go through each entity and create a new row that has the current time for last_updated, and this is fine. But if the state hasn't changed (simple string comparison), then the last_changed will copy the value from the previous entry. Or you can leave it null if it hasn't changed and that would still work.
Do you see any issues with this approach?

![image](https://user-images.githubusercontent.com/793611/110268068-be223900-7fc9-11eb-8d8d-d91c9fa9eb8d.png)

**Comment by SaturnusDJ** [comment]
@frenck 
I will provide some context on myself and probably a lot of HA users, because a simple "*I cannot program*" is often not taken well by the ones who can. I am an advanced user who goes beyond the GUI; thus YAML and Jinja2. One could see me as the system and network administrator. Often scripting comes around the corner...some basic Bash. But that is where it ends. Before, one could argue that I might be 'lazy', but last year I tried Java for weeks and absolutely disliked it. I have no natural feeling for it. I am willing to give Python a chance, but even if it would be okish, it will take months and months of dedication to reach the level required to contribute in a qualitative way. Also that is not feasible for my current and near future circumstances. With that said, I tend to have a feeling for finding flaws in programs that the average user does not find...technically, usability, interface, etc. and based on that give feedback or suggestions for improvements.

Compared to my opening post almost 2 years ago, I did get a better understanding of how programmers do not always have the time to look into things that are perceived to me as fundamental flaws or obvious things to improve. The resources are scarce on big projects as HA.

Therefore I understand that the combination of both factors results in items like these not getting 'solved' so easily. So it will depend on the voice of the community to make clear if they really want this changed and/or the willingness of someone in the community to program it.

@azogue has written code that worked for me in most ways, but as can be read it also brought a problem. Maybe he or 
someone else can build onto that.

**Comment by frenck** [comment]
@SaturnusDJ This is not a feature request forum, this is the architecture repository. One goes here for requesting/getting an architectural change approved for implementation. But it sounds like you are not planning on implementing it?

If so, even though, many people want this feature, I suggest closing this until someone can set up an actual architectural proposal that.

**Comment by SaturnusDJ** [comment]
As far as my understanding of it goes, I thought it is not a feature request but an architectural change. I cannot write it.

Is there any hint to what an architectural proposal means in this context? I suspect even that would go beyond my knowledge as it might require understanding of the HA Python code.

**Comment by frenck** [comment]
Yes, it involves Python code, as that is what is used to create the Home Assistant Core.

I'm going to close this architectural issue, as it cannot lead to anything at this point; as you have clearly shown not to be implementing this and is merely an extension of the topics already listed in the openings post.

This is not a feature request forum.

If anyone wants to implement this; We are happy to see an architectural proposal with suggestions around implementation details that can be discussed. 👍

**Comment by SaturnusDJ** [comment]
Roger. Thanks everyone for contributing. Hope to see someone taking it to the next level. 👋

**Comment by bdraco** [comment]
Proof of concept implementation here https://github.com/home-assistant/core/pull/68488

**Comment by MathisP75** [comment]
If this isn't the right place for this issue (which is still present after all these years), where is the issue on the Core repository? I have done extensive research and haven't been able to find one.

**Comment by andriej** [comment]
There's none. You've just witnessed biggest unseen elephant in the room.
