### ISSUE TITLE
Climate 1.0: auto/heat_cool clarification

### ISSUE THREAD

**Issue by andrewsayre** [home-assistant/architecture#260]
## Context

Climate 1.0 defines `auto` and `heat_cool` as follows:

```python
# The temperature is set based on a schedule, learned behavior, AI or some
# other related mechanism. User is not able to adjust the temperature
HVAC_MODE_AUTO = 'auto'

# The device supports heating/cooling to a range
HVAC_MODE_HEAT_COOL = 'heat_cool'
```

This causes confusion and complexity because most thermostats have a mode called "Auto" that resembles how we defined `heat_cool` -- not `auto`.

## Proposal
1.  Rename `auto` to `program` (`HVAC_MODE_AUTO` --> `HVAC_MODE_PROGRAM`) to represent an operating mode that has no set-points the user can adjust.
1.  Rename `heat_cool` to `auto` (`HVAC_MODE_HEAT_COOL` --> `HVAC_MODE_AUTO`) to match how the majority of devices refer to the name and implement the functionality as well as how most people will understand `auto`.

## Consequences
1. Better alignment with how users will understand the terms -- less bugs in integrations, fewer user reported false-positive issues.
1. Easier to implement and maintain integrations as it follows the conventional wisdom
1. Recently migrated platforms may need to be updated -- though some have already mapped `AUTO` and `HEAT_COOL` incorrectly due to this confusion and wouldn't need to change if this proposal is adopted (which would need to change otherwise).

**Comment by OttoWinter** [comment]
100% agree. I would add that it is even more confusing because just "HEAT" or "COOL" stand for manually forcing the device to heat or cool mode. But put together, they mean a totally different thing.

I think I see where this came from: Actions with Google - they also use heat/cool for "auto" mode. But that doesn't mean we have to use that confusing name.

**Comment by elupus** [comment]
I just want to add that even in the new PROGRAM mode, the integration might know the target temperature. So GUI should not assume it's unknown just because it's controllable.

**Comment by andrewsayre** [comment]
> I just want to add that even in the new PROGRAM mode, the integration might know the target temperature. So GUI should not assume it's unknown just because it's not controllable.

Agree -- it should always show the set points as long as they don't return `None`.

**Comment by pvizeli** [comment]
I follow the direction of Google and HEAT_COOL represent that better in my point of view, what they do. I vote for rename only `HVAC_MODE_AUTO` to `HVAC_MODE_PROGRAM`

**Comment by balloob** [comment]
I am with @pvizeli . I prefer HEAT_COOL over AUTO. Auto is ambiguous

**Comment by reharmsen** [comment]
>     1. Rename `auto` to `program` (`HVAC_MODE_AUTO` --> `HVAC_MODE_PROGRAM`) to represent an operating mode that has no set-points the user can adjust.

I disagree with program mode...
I have a thermostat that has a 'manual' mode in which you define a target, but also has a auto/program mode with a schedule. At each scheduled point the thermostat switches to the predefined setpoint.
But I am still able to adjust/change the setpoint when I want (it wil just be reset when the next scheduled point arrives)

**Comment by balloob** [comment]
Auto is not too bad then, heh 😉

**Comment by andrewsayre** [comment]
> I have a thermostat that has a 'manual' mode in which you define a target, but also has a auto/program mode with a schedule. At each scheduled point the thermostat switches to the predefined setpoint.
> But I am still able to adjust/change the setpoint when I want (it wil just be reset when the next scheduled point arrives)

I think what you're describing in that case is `auto` (or `heat_cool` per @balloob and @pvizeli preference) since you can still adjust set-point(s).  That doesn't preclude it following a schedule.  Almost all thermostats are going to work exactly as you described.

Do you have an alternative label for what I proposed for `program` where you _can not_ set the temperature points manually?

**Comment by pvizeli** [comment]
> I think what you're describing in that case is auto (or heat_cool per @balloob and @pvizeli preference) since you can still adjust set-point(s). That doesn't preclude it following a schedule. Almost all thermostats are going to work exactly as you described.

Not realy, that is `heat` if you don't want use `auto`. @andrewsayre you need open your scope :) there are a lot system around and every country is different. I needed full 2 days until I understand how a hvac work around the world. If you are family with 1-2 platforms, it would be wrong to vote for other platforms and that was the issue why climate going wrong in past. Every change on core model was only focus to a small subset of hvac universe. There is now a model they cover a lot climate but that mean also that on some platforms need have a rethinking how some things work and open the scope for more.

**Comment by dgomes** [comment]
>  I needed full 2 days until I understand how a hvac work around the world. 

It's not just a matter of "around the world". HVAC systems are by definition heterogeneous (it's in the acronym!)

Why not subclass Climate into:
- Heating
- Ventilation
- Air Condition

**Comment by OttoWinter** [comment]
@dgomes We just had a major refactor of the climate model based on lengthy discussions in another arch issue - what you're suggesting would be another one. I think we should not re-start the entire base discussion again - this thread is about changing a small aspect of the new model.

> I am with @pvizeli . I prefer HEAT_COOL over AUTO. Auto is ambiguous

I understand auto can be a bit ambiguous, it certainly could mean a lot of things. But what I don't understand why we then keep on using the word "auto" at all.

The fundamental problem (I think) is that the word `auto` is used for both modes: "program" and "heat/cool to a target".

Yes each HVAC system has their own definition of what "auto" means and we need a unified abstraction for it.

But why would we then keep on using the word `auto` at all? If we use `auto`, everything will be very confusing because our `auto` is not (in probably majority of HVACs) what the manufacturer calls auto. IMO, we should ban the word `auto` in our backend because (in your words), it is ambiguous.

Even more: It appears the frontend translates `heat_cool` to "Auto" ([link](https://github.com/home-assistant/home-assistant-polymer/commit/4fdbec93b3ae9085824d4e179874bcbdccf752f3#diff-571ce32a17d6aa22fdd0942224a8ff44R181)). Which will be super confusing when creating automations for setting a hvac into a certain mode. The user will type create a service call that sets "auto" mode, but that will fail because they _should have_ used `heat_cool` instead. *If we're going to use `heat_cool` for the backend, we should also use that word in the frontend, right?*

Maybe one option would be to remove `auto` altogether, and do this:

 - heat/cool -> heat/cool
 - auto -> program

Then we at least don't use the confusing `auto` word anymore.

**Comment by dgomes** [comment]
I think the major refactor (Climate 1.0) did not incorporate enough the lengthy comments of the various issues opened so far. And I hope I'm wrong, but I foresee a "Climate 2.0" in a not so far future, simply because many issues were not addressed (just look at all the new issues/comments).

Most of the debate comes down to how different equipments are. That's why no real conclusion was reached before. 

This minimum common denominator approach (Climate 1.0) is good because it brings all platforms into a common ground. But since it strips away most of the features it serves no real purpose :(

Getting back to this issue: Users would get really confused if we use names different from their system.

**Comment by OttoWinter** [comment]
> Getting back to this issue: Users would get really confused if we use names different from their system.

I totally agree. But on the other hand what the user is expecting can't be used as a generic definition. The fact is that auto _is_ ambiguous in HVAC systems but we need to have a system that clearly defines these modes.

What my previous post was about is why we would still use `auto` - that's something I can't understand and makes everything that much more confusing.

Maybe there is a solution to this: @pvizeli Do you know if some "program" systems also support "heat/cool" mode? If not, we could maybe make that an support flag showing what "auto" means for the particular device. It's not nice but then at least we could use `auto` which is "what the user expects" and the backend can handle what auto actually means for the device.

**Comment by pvizeli** [comment]
I'm sorry, there was a misinterpretation of my answer. That was no attack to anything. Well, it's only a developer flag and will be translated and show to the user in different ways. I say only `HEAT_COOL` should not be changed because it shows what they do. If that now called `auto` or `program` is not an issue to me.

The integrator of that integration can decide if they want to use `auto` or if that makes sense that the user can change the temperature manually as `heat`. Maybe we can add a flag for `auto` too for let change temperature also if they run in presets or other called predefined temperatures.

**Comment by OttoWinter** [comment]
@pvizeli No no, I did not read it as an attack (nor was my answer supposed to be one fwiw). I just wanted to get this done before the next release so that we can change this before it becomes a breaking change.

To clarify, my objectives are (in this order):

 1. Do not use `auto` at all - Using `auto` for just the "non target settable mode" is really weird and will be confusing for users because they think the "auto" they see in frontend is also called "auto" in automations, which it is not. So rename current `auto` to `program`

 2. If possible, merge `heat_cool` and `program` into `auto` again - Reason is: auto is just what the user is used to as a name for their device. Of course that would mean adding a new attribute for differentiating between `auto` = `heat_cool` or `program` mode (as described before).

I understand (2) might be a bit hard to push (bc it would be a new attribute), but I'd like to attempt getting (1) into the next version before it becomes a breaking change and because there appears to be support for that suggestion here.

**Comment by pvizeli** [comment]
@dgomes split up is possible and Ventilation exists already and is called `fan`. So you have for 1 device 1-3 cards. You run only into the issue for AC and H devices in the same type. In that case, it's strange to handling with split up H from AC. But that affects only around 25 integration.

You can give a draft 👍

**Comment by dgomes** [comment]
I was proposing subclassing instead of splitting... point being that they would all share the same common properties and eventually the same card.

**Comment by andrewsayre** [comment]
I think eliminating the usage of `auto` solves the majority of issues.  I'm fine to move forward only renaming `auto` to `program` and leave `heat_cool` as it is.  The frontend should then also show 'Heat/Cool' as a label instead of `Auto`.

**Comment by moustic999** [comment]
most of the thermostat when running in "scheduled mode"let the possibility to the user to increase/decrease target temperature. Most of the time up to  the next setpoint change. Whatever the mode is called AUTO or PROGRAM, let allow the user to override the temperature.
maybe the mode when running from calendar scheduler should be called `scheduled`. auto and/or program are not very clear.

**Comment by andrewsayre** [comment]
@moustic999 I think the defining characteristic of `program` (called `auto` today) is that it does NOT have set-point(s) that can be changed by the user.  Thermostats can follow a schedule in `heat`, `cool`, `heat_cool`, `fan_only`, etc...  The defining characteristic of these modes is the type of HVAC supplied (heating, cooling, fan, etc...) and has one or more target set-points that can be changed by user.

**Comment by balloob** [comment]
Opened a frontend PR with the rename: https://github.com/home-assistant/home-assistant-polymer/pull/3363

For the backend, I think that a lot of places that are using HVAC_MODE_AUTO, they should be changed to HVAC_MODE_HEAT_COOL instead of HVAC_MODE_PROGRAM. Do we know of any integration that should use `HVAC_MODE_PROGRAM` instead of `HVAC_MODE_HEAT_COOL` ?

**Comment by moustic999** [comment]
@andrewsayre maybe I did not explained correctly. I agree that in Scheduled mode user can't change the setpoint. What I mean is, user is always able to override the current target setpoint temporarely. all thermostat have + - buttons to change the target temp. this works even in scheduled. that override the scheduled setpoint till the next change.

**Comment by andrewsayre** [comment]
@moustic999 yes I understood that :)

**Comment by pvizeli** [comment]
You speak about option to allow set a temporary setpoint on program mode

**Comment by cgtobi** [comment]
The Netatmo thermostat for example allows always to override the current set point. It keeps that set point for 2 or 3 hours by default and turns back to the original schedule. This also works with the new climate component. Just my 2 cents.

**Comment by Jc2k** [comment]
Was there an outcome for this? A related PR was closed, and we are starting to see confusion about the change, e.g. https://github.com/home-assistant/home-assistant/issues/25233 mentions the auto mode rename. Should I tell users that the new name is final, or might it still change to 'program'?

**Comment by balloob** [comment]
New name is final. There didn't seem to be much animo for the change. Let's focus on teaching the right thing. If your thermostat is on a schedule, it's auto. If it's temporarily overridden to a range, it's heat cool.

**Comment by glmnet** [comment]
I just wanted to share here my AC which supports cooling only how can I set it up in Heat / Cool mode 

![image](https://user-images.githubusercontent.com/96162/68717543-d759d780-0585-11ea-9059-b14ae0a51466.png)

I'm working right now on adding ESPHome ability to set DRY and FAN_ONLY mode, and stumbled upon this.
I'm not upset not I want this to be changed or anything, and I do appreciate all the work done here. But just wanted to share it 😊
To be honest, I really don't know what Auto means in my AC remote, but the option is there and the thing turns on in "Auto", but it only supports cooling.
