### ISSUE TITLE
Entity Management

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#276]
## Context

We have had some ADRs merged (like 003, removing monitored conditions) and are migrating device tracker over while not fully supporting all features device tracker offered, and there is some confusion about the goal. I want to clarify.

## Proposal

The goal is to have Home Assistant allow managing entities instead of each integration doing it on their own, in their own style/manner.

By having a unified way of doing it, we can allow a single way of YAML configuration and a single way of managing it in the UI. 

The key to all this is the entity registry. The entity registry has a `disabled_by` field. If an entity is disabled, it will be dropped while it is being processed by `async_add_entities`.

This will work for polling integrations out of the box. Since they update when Home Assistant polls them, by not being polled, they will just stop existing.

For non-polled entities, it is important to only start listening for entity updates inside the `async_added_to_hass` hook. 

@Kane610 has been working on adding some of the device tracker features to Home Assistant. The most important one is config entry system options. The first option that will be introduced is a "disable new entities for config entry" (https://github.com/home-assistant/home-assistant/pull/25926). This means that if an integration adds a new entity, it will be disabled if the option is set to true. This mimics one of the device tracker features: `track_new_devices: false`.

The other option that we are introducing (https://github.com/home-assistant/home-assistant/pull/26011) is that integrations should be able to indicate on entities (via a new property) if an entity should be enabled/disabled by default. That way, in the case of `netgear_lte` which has 400 entities, we can enable a default set of useful entities, but allow users to manage other entities to enable/disable. 

Note that we do not currently have a way yet of informing integrations when an entity has been enabled again. We could do this by reloading the config entry (`await hass.config_entries.async_reload(entry_id)`).

## Consequences

- A unified way for users to manage entities in Home Assistant.
- Integrations focus on pulling data in and offering control. Not on data management.

**Comment by Kane610** [comment]
Allowing integrations to indicate entities that should be enabled/disabled by default is something I got a request for recently as well. 👍

**Comment by amelchio** [comment]
Yeah, I am confused. Maybe not so much about the goal but about moving backwards to get there.

ADR 3 prohibits integrations from doing entity management on their own. Some concerns about performance and clutter were raised but ignored. So now affected contributors cannot do it the old way because it is banned and they cannot do it the new way because it does not exist.

In ADR 4 affected contributors are told to just make a custom component while the custom component experience is quite subpar.

It’s nice with plans such as those outlined in this issue, thanks. I just think we should be more careful about not taking things away until replacements actually exist. It’s quite alienating for contributors.

To make this post less meta, I propose that we do not enforce ADR 3 until the goal in this issue is implemented.

**Comment by balloob** [comment]
0.98 will have all the necessary things in place. You're right in that we can do a better job in landing things in the right order.

**Comment by frenck** [comment]
Closing this proposal, as all have been implemented and fast forward to today; this is all pretty normal now.
