### ISSUE TITLE
Allow selecting source for media_player when off + handle turn on

### ISSUE THREAD

**Issue by ktnrg45** [home-assistant/architecture#327]
## Context

There is no user friendly method to **turn_on** a media_player and then **select_source** automatically.

I compare the source attribute of a media_player to the brightness attribute of a light entity. For example, the light entity card in the frontend and so the turn_on service, allows users to have the option to select brightness and thus turning on the light automatically, or an option to simply turn on the light. This adds to the user experience and as well adds convenience.

Now similarly, if a user wanted to turn on a media_player and then trigger the select_source service automatically, they would have to create an automation or script.  This would involve creating an automation triggering the turn_on service and then the select_source service. Additionally users may have to time service calls ie. wait for device to turn on, then trigger select_source service; by using events, delays, conditions, etc. However this adds complexity for the user, as well as requiring the user to maintain an automation for each source they would want to select, which ultimately can cause a lot of headaches, detracting from the user experience. This is apparent with the PS4 integration as some users on the community forum have trouble with automating this, since the PS4 console will reject connections until it is ready. 

While we can abstract this particular action in the backend via the select_source service call per integration currently; when an entity's state is 'off', there is no indication from the frontend card that this service would be available as the source selector drop down is hidden.

## Proposal

Some implementation options:

1. Add an additional state: **standby** for example, as a valid state for media_players. I'd define it as a similar state to 'off' but allows for select_source to be called from the frontend/lovelace, as long as the integration handles turning on the device and scheduling the select_source call. The card will not hide the source drop down as is.

or

2.  Add a supported feature mask and add the definition to frontend so that source drop down is not hidden when state is off.

## Consequences

The user example in **Context** will be easier for users.

@ option 1: Risks include glitches/bugs from code for which the entity state needs to explicitly be 'off'. This is apparent for at least the Homekit and Universal integrations.

**Comment by fleXible** [comment]
Hi, I'd prefer to first sort out the current "STATE_STANDBY missing from media_player" issue, before attacking this related select_source thing.

**Comment by ktnrg45** [comment]
> Hi, I'd prefer to first sort out the current "STATE_STANDBY missing from media_player" issue, before attacking this related select_source thing.

Hi thanks for the comment, I'd also prefer to do that as well as then the whole select_source thing would become available to use on it's own. I suppose I am trying express some sort of justification or a use case to have such a state be added to the architecture in the first place and the intended effect. I would rather not have STATE_STANDBY as a state if the only difference from STATE_OFF was the name if that makes sense.

I guess the issue here is:
1. Should we make the SELECT_SOURCE feature available in the front end card when the media player is in an off-like state provided we handle the powering on sequence? 
2. If yes, then is STATE_STANDBY the way to handle this?

**Comment by fleXible** [comment]
My reasoning for pushing it is, even if not officially in the architecture for media_player the whole things just shows, how confusing and bloating this thing became. I don't see a greater good being able  to differentiate between off and standby.

It just looks like people "found" the state, thought is was not too off, and just used it, instead of the proper OFF, without further thinking. And after some time you just end up in the mess we are, where all over the place this just "kind of work", but not really.

This brings me to your question and my thoughts for that:

1. I think you already said, you see SELECT_SOURCE like color or brightness with light. For me it's exactly the same. And there is a perfectly fine way to "turn on" a TV, it will just resume showing the last channel before it was turned off. But there are a lot more case, you want your TV to do something specific when turning it on, like going to channel 7, or HDMI-2. And when talking about automation, there is no reason why I shouldn't be able to set the volume at the same time.
2. Probably not. From user perspective, is there any real difference between STANDBY and OFF but 3 Watt per hour? I don't really see those corner-cases, where you want to make a difference between those two. In the end, it's just gonna be confusing, right? Just think about TV remote control.
3. This would also mean to regard IDLE as ON and make sure, those devices like Kodi or Amazon can properly be turned on and off, instead of misusing this state. Actually IDLE can serve a purpose in, when a device is IDLE for too long, usually it will save energy and SUSPEND at some point ;)

**Comment by ktnrg45** [comment]
Ok so do you think its best that this be closed and then a new issue opened for just adding STATE_STANDBY?

**Comment by fleXible** [comment]
For now, yes. If you really think STATE_STANDBY has a solid grounding for getting that treatment.
