### ISSUE TITLE
Add device classes for electrical measurement

### ISSUE THREAD

**Issue by fabiocastagnino** [home-assistant/architecture#397]
## Context
Some energy meter read dimensions that HA can handle only as generic.

## Proposal
Add 4 new device classes for electrical measurement

- Core PR: https://github.com/home-assistant/core/pull/36800 
- home-assistant.io PR: https://github.com/home-assistant/home-assistant.io/pull/13756
- developers PR: https://github.com/home-assistant/developers.home-assistant/pull/579

## Consequences
Sensors (template, zha, etc) can use more specific device class for electrical  measurement

**Comment by MartinHjelmare** [comment]
I think we should go ahead with this.

**Comment by balloob** [comment]
I say we drop power_factor. We cannot have a device class without a unit.

**Comment by MartinHjelmare** [comment]
Why not?

**Comment by thomasloven** [comment]
That should be adressed. `one` or `1` is a valid SI unit.

**Comment by balloob** [comment]
Sensor integration contains of three types of sensors: numeric, enum (fixed number (3+) of values) and free text. Right now all device classes are part of numeric sensors. All numeric sensors have a unit, that's why we know it's numeric. Allow above/below automations, option to graph etc. 

Having a numeric sensor be without a unit is different. We should not just pass that without considering all the checks. It all of a sudden means that we no longer can just check if there is a unit if we should graph it, we also need to check the device class in case it's this one rare device class that has no unit.

**Comment by MartinHjelmare** [comment]
The point of device classes is exactly to define what type of measurement the entity provides. The frontend should primarily use the device class when making those kinds of decisions, graph or not etc. Unit of measurement can be a fallback.

**Comment by balloob** [comment]
That's true. Device class is more important. 

So how come there is no unit? Isn't "factor" the unit ?

**Comment by BradleyFord** [comment]
This thread seems to have the best answers.
https://www.quora.com/What-is-the-unit-of-a-power-factor

So we could either have the units as:
1. "p.f."
2. "%" (and multiply the value by 100 as it is always between 0 and 1)

**Comment by MartinHjelmare** [comment]
I kind of like percent.

@fabiocastagnino do you have a preference?

**Comment by dgomes** [comment]
The actual unit is φ (cos-phi)

**Comment by MartinHjelmare** [comment]
My understanding, from reading wikipedia and other sources, is that phi is a label given to the angle between the vectors of real power and apparent power in the power triangle. Cosinus phi is then the power factor. Sometimes the angle is labeled as theta instead of phi.

So cos-phi is not the unit of the power factor, it's the representation of the power factor in some vector space.

**Comment by fabiocastagnino** [comment]
> My understanding, from reading wikipedia and other sources, is that phi is a label given to the angle between the vectors of real power and apparent power in the power triangle. Cosinus phi is then the power factor. Sometimes the angle is labeled as theta instead of phi.
> 
> So cos-phi is not the unit of the power factor, it's the representation of the power factor in some vector space.

I totally agree. I think that the best unit is %

**Comment by jjlawren** [comment]
Power factor does not have a unit. It is a numerical ratio between two measurements of the same unit.

**Comment by dgomes** [comment]
https://library.e.abb.com/public/903a65b9e3cb6340c1256f2e003fa9f3/2GCS201015A0050.pdf

This is manual for a power factor controller, pay attention to the unit showed in the HMI

**Comment by fabiocastagnino** [comment]
![Screenshot_20200731-221834_OneDrive](https://user-images.githubusercontent.com/9453234/89074010-d2d78800-d37b-11ea-8879-fdf79e4be3c1.jpg)

This manual confirm that cos φ (cos-phi) is pure number, and don't have unit of measurement.
