### ISSUE TITLE
Handling of dynamically provided backend strings

### ISSUE THREAD

**Issue by benoitlouy** [home-assistant/architecture#47]
According to this comment 
https://github.com/home-assistant/home-assistant/pull/15083#discussion_r203446026 all backend strings must be lower snake case. The frontend and the translation components are in charge of displaying the correct string in the UI.

This works if we know in advance all the possible backend strings used by a component. However in the case of dynamically provided strings, an exhaustive translation cannot be provided.

For instance the input sources of a media player component can be provided by the device/service itself.

How can we handle such cases?

**Comment by balloob** [comment]
I think that we should not try to translate those at all. Just show them as we get them from the API?

**Comment by armills** [comment]
I'd personally be OK with accepting that source options are going to be human friendly strings. It does mean that if you use them in automations you'll have to use human friendly names as part of your code, but I think that's probably the most straightforward option.

I think that's been the defacto standard so far, but I don't know if we've formally decided that, since it runs counter to the way we handle most of our attributes.

**Comment by balloob** [comment]
We should add it to the [docs](https://developers.home-assistant.io/docs/en/entity_media_player.html)

**Comment by MartinHjelmare** [comment]
Why should the backend care about frontend formatting?

We should be consistent in the backend to make it easy for users with automations.

The frontend should handle its formatting.

**Comment by armills** [comment]
I'd certainly be open to a proposal for a better way to handle this.
