### ISSUE TITLE
Remove unit_of_measurement from climate object state

### ISSUE THREAD

**Issue by reevery** [home-assistant/architecture#48]
As requested in Lovelace UI https://github.com/home-assistant/ui-schema/issues/137

The entity climate includes the status (on/off/cool/heat) and the unit_of_measurement attribute. In the current UI, the entity is displayed with current_temperature, and target_temperature, presumably why unit_of_measurement is available. 
![image](https://user-images.githubusercontent.com/4381067/43210193-55e7266a-9026-11e8-878e-180f79801556.png)

Lovelace only shows status and unit_of_measurement, which makes no sense:
![image](https://user-images.githubusercontent.com/4381067/43210325-ae5301ca-9026-11e8-9c20-62bf64d56686.png)

**Comment by c727** [comment]
Background:
- the attribute describes other attributes and not the state
- we can use core.unit_system.temperature instead

**Comment by balloob** [comment]
I agree, we should only add `unit_of_measurement` if it descdibes the state and the state is numeric.

**Comment by arbreng** [comment]
This is relevant to the [Cooker Entity](https://github.com/home-assistant/architecture/issues/51) too, as it includes a unit_of_measurement.

I always assumed that unit_of_measurement was meant to tell which unit systems the device/sensor is reporting in.  core.unit_system.temperature is for describing which units the user selected in their configuration.yaml, right?

This means that they are 2 different things, and they can vary independently.  There are 4 states to be accounted for here if you are considering combinations of F and C.  Some thermostats (and cookers) allow adjusting their measurement unit independently of HA, so unfortunately we could never escape this situation entirely.

I do agree with @c727 that the frontend should just use core.unit_system.temperature.  After all, that is what the user chose!

However, internally it seems the platform would need a unit_of_measurement.  Systems like Google Assistant and Alexa need that unit, because their incoming data is always in Celsius.  If we don't know what unit to convert to, things will break.

We can change the climate/cooker to always report their temperatures in Celsius, which solves this problem, but we will then need to do a conversion in the frontend and (potentially) internally to each platform.

So, I think that unit_of_measurement has a real purpose and we can't eliminate it entirely.  However it would still be possible to remove it from the frontend and the state if we want (just keep it internal to the platform).

**Comment by balloob** [comment]
Entities will convert their state values into the temperature unit used by core. This is currently done in the Entity base class but should be moved to a Sensor base class.

All entities should be written to the state machine in the unit that is the preference of the user.

**Comment by balloob** [comment]
All yes except for 3, as that is already happening.
