### ISSUE TITLE
More Weather Component Properties

### ISSUE THREAD

**Issue by randellhodges** [home-assistant/architecture#75]
I'd like to add dew_point as a property and forecast attribute and also see that for any "current property" such as humidity, they are acceptable as a forecast attribute (assuming the data source has it).

Add following as forecast attribute:
- dew_point
- pressure  (a current property)
- humidity (a current property)
- ozone (a current property)

Add following as current properties:
- dew_point

I could see the benefit of "feels like" (which would be heat index/wind chill).

Submitting this as requested by @pvizeli  for the code review comment on https://github.com/home-assistant/home-assistant/pull/16719

**Comment by fabaff** [comment]
The dew point is available from ZAMG and Dark Sky but not from OWM or Yahoo. I haven't check the other platforms. Thus, they may provide it as well. As I already told in [this comment](https://github.com/home-assistant/home-assistant/pull/16719#discussion_r219895554) should we aim for the values which are the most common. The downside of this approach is that we might limit the user experience. As there is more than one platform that has those values, let's add them because there is a chance that other services may include it too.

**Comment by balloob** [comment]
Instead of making things official attributes, the few platforms that have it can add it to their forecast data. Making something official means we need to add UI support.

**Comment by randellhodges** [comment]
If 2 or more platforms can add it to their attributes, should we define the attribute in the base class?

That is what I originally did but was asked to remove it and post here.

On to official and UI support. Can this also be something where the UI displays it, if available?

I think so, but there can be a lot of current/forecast conditions and that could lead to clutter. That might be part of the reason I was asked to open this issue.

**Comment by victorcerutti** [comment]
Hi,
I'm jumping into this request as I'm working on a new platform for the weather component.
I'm retrieving data from the Météo-France weather forecast which are quite different from other sensor. I don't have humidity, pressure or ozone attributes which lets the weather card a bit empty

What I have is a 1 hour rain forecast (pretty accurate), and some other attributes like risk of thunderstorm, freezing, etc.

As all platform have different datas, maybe the best solution is not to list all attributes but that each platform returns a dictionnary of the datas that should be displayed on the weather card

**Comment by victorcerutti** [comment]
What would be interesting is to let the platform decides which attributes to display.

If there is a 0% chance of thunderstorm, maybe the information is not worth showing on the card
Instead if there is a freezing chance of 50%, then let's display it

This could also be used to display some weather alerts directly on the weather card (if available in the platform)

**Comment by fabaff** [comment]
> What would be interesting is to let the platform decides which attributes to display.

I assume that this can already be handled by Lovelace.

> This could also be used to display some weather alerts directly on the weather card (if available in the platform)

Alerts should be handled by the `geo_location` component which would be easy if there is component for the weather service integration in question.

**Comment by MatthewFlamm** [comment]
Please let me know if you would rather a new issue for this.

I would like to make two requests, both related to a US NWS platform for the weather component I've been working on.

1.  Probability of Precipitation be added as a supported value for forecasts in the back/front end.
  a.   This is the default forecast type in the US.  Precipitation amount, which can be currently shown, is usually relegated to extraordinary conditions or winter precipitation.
  b.   I propose that both % and amount of precipitation be shown if available from the platform.

2.  A day/night forecast in addition to once daily and hourly
  a.   Again, this is the default forecast type that I am used to in the US.
  b.   The current daily forecast just displays the day of the week, while the hourly displays day of the week plus the time below.  I propose that this new mode displays day of the week plus "Night" below if it is nighttime forecast, otherwise nothing below.  So we would have "Mon", and "Mon/Night" for example.

I already have both of these implemented in the front/back end in the weather component - it looks very nice IMO - but I wanted to get feedback on whether this would be welcome or not.  If OK, I also wanted to get feedback on whether these changes should be done separately to submitting a new weather platform.

**Comment by michaeldavie** [comment]
I would support adding a "feels like" temperature to the current conditions, as this is a commonly referenced data point in my region (Canada) in both winter and summer. Our national weather service also includes a "likelihood of precipitation" value in their daily and hourly forecasts as a percentage, and I think that would be useful to display as well.

**Comment by victorcerutti** [comment]
Every sources for weather datas might have different attributes (feels like, precipitation or freeze likehood, visibility, air quality, … for the current condition or the next days forecast)

I think each platforms should be able to display on the UI its particular attributes.

Another solution would be to have specific custom lovelace card for different weather provider (official or custom) but it seems more work and harder to maintain.

**Comment by Rontruong** [comment]
Hi I'm quite new to home assistant.  I love the weather card. Is there some way I can add that to my config?

**Comment by thomasloven** [comment]
This is not a support forum. https://www.home-assistant.io/help/

**Comment by thomasloven** [comment]
> Hi I'm quite new to home assistant. I love the weather card. Is there some way I can add that to my config?

This is not a support forum. https://www.home-assistant.io/help/
