### ISSUE TITLE
Deprecate CONF_MONITORED_VARIABLES in favor of CONF_MONITORED_CONDITIONS

### ISSUE THREAD

**Issue by cgarwood** [home-assistant/architecture#84]
`monitored_conditions:` and `monitored_variables:` both seem to do/mean the same thing. A quick search through the `components` folders returns 75 files using `monitored_conditions` and 15 using `monitored_variables`

I propose getting rid of monitored_variables and updating the 15 components using it to use monitored_conditions instead, to help simplify configuration.

**Comment by fabaff** [comment]
Introducing a breaking change for 15 platforms? Not a good move from my point of view especially at the moment as Quality scale is here. I don't see how this should simplify the configuration because the configuration will still not be interchangeable between the platforms. Now it could lead to two breaking changes in a row. First renaming of a configuration variable then making the platform ready for a better grade.

**Comment by balloob** [comment]
Although we can choose to leave the existing as-is, we can at least make a decision what future integrations should use and document it in the dev docs.
