### ISSUE TITLE
Reduce templating entities renders

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#85]
A template entity (sensor, switch, etc) has to render whenever states it depends on are changing. This detection is done using a regex which is not always correct. If the regex cannot detect it, the template sensor will render on **every** state change. This is impactful. To limit this, we already have an option for template entities to specify which entities to rely on, however it's optional.

The goal should be too limit useless renders of template entities as it's causing slowdowns and timers going out of sync. I think @arsaboo linked me a post on the forums some time ago where the solution that people found was to link certain templates to a time sensor that was changing every second. (sorry, can't find blog post anymore)

This got me thinking this morning, we should limit rendering.

Proposal:

 - If entity ID specified to track, don't limit anything
 - If listening to all state changes, we should add a cooldown of 1 second. If a state change comes in during the cooldown, we will schedule an update as soon as the cooldown expires. This means that a tenplate entity could be trailing the real state up to a second, that's not a bad trade off.

**Comment by pvizeli** [comment]
The regex was a optimize for asyncio because 99% of user don't use entity_id option and all templates rendering all time every state change. With this function, we can detect the entity_id in a lot of cases for normal simple template sensors they was used by normal users.

There are a lot complex template sensors around and users they are able to write such templates could also understand how this option work.

Anyway, I think for 3te options:
- If the regex function don't detect a valid entity_id, the entity_id is not optional in that case the user need set a entity_id or set it explicit to listen all.

@balloob point 1 should be already work in that direction. We use the regex only, if user don't set one.
