### ISSUE TITLE
Split interval from time trigger

### ISSUE THREAD

**Issue by armills** [home-assistant/architecture#88]
## Description
Currently, [the time trigger supports one of two exclusive configurations](https://www.home-assistant.io/docs/automation/trigger/#time-trigger). `at` can be specified, to have the trigger execute at a specific time, or `hours`, `minutes`, and `seconds` can be specified to have it run on a regular interval. This is currently [complicating the frontend implementation](https://github.com/home-assistant/home-assistant-polymer/pull/1724), and beyond that it seems like we've combined two trigger definitions into one platform.

I'm proposing that we split these into two trigger types. A `time` trigger that only supports the `at` syntax, and an `interval` trigger that can be configured with `hours`, `minutes`, and `seconds`. For the initial rollout we can continue to load `hours`, `minutes`, and `seconds` for `time`, and just flag them as deprecated to prevent an immediate breakage.

**Comment by amelchio** [comment]
A bit of a tangent but I identified a performance issue in #50:
> Also, the flexible time patterns made me unable to calculate the duration until the next matching time. For example, `minutes: /59` will fire 120 seconds in a row and then pause for 3480 seconds. I tried some optimizations but it gets messy real quick.

If we are making a breaking change here anyway, maybe we can consider making the `interval` type trigger less flexible so it is possible to calculate the sleep time until the next event.

As it stands today, each trigger has to be checked every second.

**Comment by balloob** [comment]
One thing that would help is to automatically default the lower units to 0. So if you specify hour=5, we default minutes and seconds to 0. Because no way you would want it to fire every second when hour = 5.

**Comment by pvizeli** [comment]
I like that Idea and I'm also with @amelchio. We are win a lot of performance if we kill our time change code and use that one from @amelchio. That would be the best performance improvement after async migration.

**Comment by armills** [comment]
👍 on refactoring the complexity with this change as well. We can have the interval trigger only support a simple time period that core can schedule efficiently.

Do we think there are any legitimate use cases for the full cron syntax? We could always create another `cron` trigger type to handle these cases. I'd be worried about completely removing this functionality if people have already built a workflow around it.

**Comment by OttoWinter** [comment]
+1 for doing this *for the reason of simplifying the config*. I have seen lots of people struggle with understanding why  `seconds: 0` is necessary.

However, I think the speed reason is invalid. Sure, currently home assistant checks every second if the time trigger matches and that is very inefficient. So what we would need would be a function `next_timestamp` that, given a timestamp `x`, would spit out the next timestamp for which to trigger.

Fortunately, that algorithm is well known for cron-style expressions (sample implementation, for C and way uglier than it has to be: https://github.com/staticlibs/ccronexpr). For esphomelib's cron syntax, I recently implemented that exact algorithm and it's really not too difficult (also because Home Assistant only uses a subset of the cron syntax, without things like `L`).

I'm currently writing a quick sample implementation of that algorithm for python and will post it here when ready.

**Comment by armills** [comment]
Looking at 1200 lines of C doesn't exactly inspire confidence that it's a trivial task, but I'm open to a more efficient implementation if you can write it. But I think the path forward for this issue is the same whether or not we have a new implementation, so I'd rather not dive into that conversation in this thread. Let's keep this discussion about the new proposed schemas.

**Comment by balloob** [comment]
I propose small steps: step 1: split it up with existing logic. step 2: add Otto's algorithm with the necessary test cases.

**Comment by amelchio** [comment]
@OttoWinter that's awesome, clever to pre-calculate the valid values. Since time triggers are in local time, do you also have a neat way to make it work across DST changes?

@balloob it almost seems like the small steps should be reversed so we are sure that we do not design something that we cannot implement (efficiently).

**Comment by OttoWinter** [comment]
@amelchio Sure, using pytz it's not too difficult to do (left it out previously because of laziness :P) I've updated the gist with it. Also, while we're at it: I think one big limitation of the time trigger is its ability to trigger on days of week. I think there are plenty of use cases where users would want to run something only on one/a few days of the week. And as long as *only one of day of week and day of month* is added, it wouldn't be a problem to implement either. What do you think?

**Comment by balloob** [comment]
Seems reasonable. However, that would be a third PR.

**Comment by amelchio** [comment]
@OttoWinter Excellent, so we can ignore my tangent.

I am not sure about weekdays, it seems like the time condition already handles that in a generic way.
